### ISSUE TITLE
OracleJava8.munki recipes failing

### ISSUE THREAD

**Issue by tbridge** [autopkg/autopkg#158]
When I run the OracleJava8.munki recipe, I am getting this:

```brookland:Cache ladmin$ autopkg run OracleJava8.munki```

Processing OracleJava8.munki...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 156, in main
    glob(os.path.join(mount_point, dmg_source_path))[0])
IndexError: list index out of range

**Comment by tbridge** [comment]
This is resolved by an update to the repo to get a new recipe.

Thanks Tim!
