### ISSUE TITLE
setup_new_recipe_repo.py fails on org source repos

### ISSUE THREAD

**Issue by timsutton** [autopkg/autopkg#206]
..because the script currently assumes the owner of the repo is the same user to add to the team.

Greg tried to add @bochoven to a new team for managing a new munkireport-recipes repo:

```
% ./setup_new_recipe_repo.py --token XXXXXXX munkireport/munkireport-recipes
Using source repo: user munkireport, repo munkireport-recipes
Will clone to autopkg/munkireport-recipes..
Fetching autopkg's public repos..
Creating new team: munkireport-recipes..
Adding munkireport to new team..
API error: HTTP Error 422: Unprocessable Entity
Server response:
{u'documentation_url': u'https://developer.github.com/v3/orgs/teams/#add-team-membership',
 u'errors': [{u'code': u'invalid',
              u'field': u'user',
              u'resource': u'TeamMember'}],
 u'message': u'Validation Failed'}
Traceback (most recent call last):
  File "./setup_new_recipe_repo.py", line 239, in <module>
    main()
  File "./setup_new_recipe_repo.py", line 221, in main
    method="PUT")
  File "./setup_new_recipe_repo.py", line 96, in call_api
    return (resp_data, status)
UnboundLocalError: local variable 'resp_data' referenced before assignment

Problem almost certainly triggered by "Adding munkireport to new team”, where “munkireport” is not a GitHub username.

-Greg
```

We should first check whether the source repo is an org and then require an additional option, the name of the user to add to a new team.

**Comment by timsutton** [comment]
Resolved in 91312a665bc7dc3c46eeb55596c4bcdf1f543080.
