### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'encode'

### ISSUE THREAD

**Issue by n8felton** [autopkg/autopkg#299]
```
$ autopkg version
0.6.2

$ autopkg search adobe

Name                                              Repo                        Path                                   
----                                              ----                        ----                                   
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1888, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1882, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 888, in search_recipes
    print_gh_search_results(results["items"])
  File "/usr/local/bin/autopkg", line 827, in print_gh_search_results
    repo = result["repository"].encode('UTF-8')
AttributeError: 'dict' object has no attribute 'encode'

```

It appears https://github.com/autopkg/autopkg/commit/b5c28e02f378dc253988479db8d9aa531afe2458 is causing issues with the current master branch.

**Comment by gregneagle** [comment]
Fixed here: https://github.com/autopkg/autopkg/commit/cacbd1a94438f23baa1e14d675cc98e4c6c5adbd
