### ISSUE TITLE
macOS 10.12 ImportError: No module named cryptography.hazmat.bindings.openssl.binding

### ISSUE THREAD

**Issue by everetteallen** [autopkg/autopkg#311]
So just in case other folks are seeing crypto errors like these:
===
 Tue Oct 11 13:45:23 on ttys000
$ autopkg repo-list
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 44, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 622, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 530, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 28, in <module>
    import jss
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/__init__.py", line 60, in <module>
    from .jamf_software_server import JSS
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 34, in <module>
    from .tlsadapter import TLSAdapter
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/tlsadapter.py", line 26, in <module>
    from requests.packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/Library/Python/2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Library/Python/2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/Library/Python/2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
===
The fix for me was:
 pip install cryptography==1.0.2
The directory '/Users/oitadmin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/oitadmin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting cryptography==1.0.2
  Downloading cryptography-1.0.2-cp27-none-macosx_10_10_intel.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 417kB/s 
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /Library/Python/2.7/site-packages (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /Library/Python/2.7/site-packages (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /Library/Python/2.7/site-packages (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in /Library/Python/2.7/site-packages (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /Library/Python/2.7/site-packages (from cryptography==1.0.2)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Library/Python/2.7/site-packages (from cffi>=1.1.0->cryptography==1.0.2)
Installing collected packages: cryptography
Successfully installed cryptography-1.0.2

**Comment by timsutton** [comment]
Since this is specifically related to `python_jss` and its dependencies, I think this issue would belong in the [python-jss](https://github.com/sheagcraig/python-jss) GitHub repo.
