### ISSUE TITLE
Missing dependencies idna and cryptography

### ISSUE THREAD

**Issue by ninjabong** [autopkg/autopkg#322]
Have been trying to get a new VM setup with autopkg to offload from my machine but keep hitting issues with both 0.6.1 and 1.0rc1 where autopkg is missing dependencies for **idna** and **cryptography**.  `sudo -H easy_install idna` works fine for the former but **cryptography** not so much as it fails to find opensslv.h. 

`sudo -H pip install cryptography` does succeed since it's not trying to compile but then autopkg fails during recipe runs erroring with [Error: 'X509' object has no attribute '_x509'](https://github.com/sheagcraig/JSSImporter/issues/94)

Following is output with **idna** installed but without **cryptography**
```
autopkg-vm:~ admin$ autopkg version
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 44, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 622, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 530, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 28, in <module>
    import jss
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/__init__.py", line 60, in <module>
    from .jamf_software_server import JSS
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/jamf_software_server.py", line 37, in <module>
    from .tlsadapter import TLSAdapter
  File "/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/tlsadapter.py", line 26, in <module>
    from requests.packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests-2.12.1-py2.7.egg/requests/packages/urllib3/contrib/pyopenssl.py", line 48, in <module>
    from cryptography import x509
ImportError: No module named cryptography
```

**Comment by arubdesu** [comment]
This has nothing to do with the code in this repo. Please file an issue on [python-jss](https://github.com/sheagcraig/python-jss)(the most appropriate location of an issue) or, if you think more people would look for autopkg-related code first, the [JSSImporter](https://github.com/sheagcraig/JSSImporter) repo.

**Comment by ninjabong** [comment]
Ahhhh gotcha - thanks!
