### ISSUE TITLE
Python "NSInvalidArgumentException" error when calling a non-existent recipe list

### ISSUE THREAD

**Issue by ejordansc** [autopkg/autopkg#375]
Looks like AutoPkg doesn't check for the presence of a file before passing it through to FoundationPlist for reading.

Example, assuming /tmp/foo.txt does NOT exist:

```
$ autopkg run -v --recipe-list /tmp/foo.txt
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2436, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2430, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1885, in run_recipes
    recipe_list = parse_recipe_list(options.recipe_list)
  File "/usr/local/bin/autopkg", line 1798, in parse_recipe_list
    plist = FoundationPlist.readPlist(filename)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 120, in readPlist
    return _dataToPlist(data)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 74, in _dataToPlist
    data, NSPropertyListMutableContainersAndLeaves, None, None))
ValueError: NSInvalidArgumentException - data parameter is nil

$ autopkg version
1.0.3
```

More desirable behavior might be for AutoPkg to throw an error stating that the recipe list does not exist at the given path.

**Comment by gregneagle** [comment]
This looks like an issue with the version of FoundationPlist included with autopkg:

```
# autopkg run -v --recipe-list /tmp/foo.txt
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2435, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2429, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1884, in run_recipes
    recipe_list = parse_recipe_list(options.recipe_list)
  File "/usr/local/bin/autopkg", line 1797, in parse_recipe_list
    plist = FoundationPlist.readPlist(filename)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 120, in readPlist
    return _dataToPlist(data)
  File "/Library/AutoPkg/FoundationPlist/FoundationPlist.py", line 74, in _dataToPlist
    data, NSPropertyListMutableContainersAndLeaves, None, None))
ValueError: NSInvalidArgumentException - data parameter is nil
```
Now I replace FoundationPlist with the one from Munki:
```
# sudo mv /Library/AutoPkg/FoundationPlist/FoundationPlist.py /Library/AutoPkg/FoundationPlist/FoundationPlist.py.old
# sudo cp /usr/local/munki/munkilib/FoundationPlist.py /Library/AutoPkg/FoundationPlist/
# autopkg run -v --recipe-list /tmp/foo.txt                             
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2435, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2429, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1884, in run_recipes
    recipe_list = parse_recipe_list(options.recipe_list)
  File "/usr/local/bin/autopkg", line 1806, in parse_recipe_list
    with open(filename, "r") as file_desc:
IOError: [Errno 2] No such file or directory: '/tmp/foo.txt'
```

**Comment by gregneagle** [comment]
So someone could fix autopkg's FoundationPlist and submit a PR, or we could just punt and replace autopkg's FoundationPlist with Munki's. Either case bears some slight risk.

**Comment by gregneagle** [comment]
(and autopkg itself needs to do a better job of capturing the exception and displaying the underlying error...)

**Comment by gregneagle** [comment]
FWIW, I'm in favor of replacing autopkg's FoundationPlist with the one from Munki. I think my intention was to improve/modernize FoundationPlist and then use the improved/more modern version in Munki. Obviously it didn't work out that way.
