### ISSUE TITLE
Install recipe (e.g. firefox) not exiting cleanly from InstallFromDMG processor

### ISSUE THREAD

**Issue by arubdesu** [autopkg/autopkg#590]
When running firefox.install or other install variants the app does end up in a working state, but autopkg thinks it failed with
```
Error in com.github.autopkg.install.Firefox: Processor: InstallFromDMG: Error: [Errno 9] Bad file descriptor
```

Only have MUNKI_REPO (/Users/Shared/repo) and basic RECIPE_REPOS and RECIPE_SEARCH_DIRS set as prefs.

```
InstallFromDMG
{'Input': {'dmg_path': '/Users/allister/Library/AutoPkg/Cache/com.github.autopkg.install.OmniDiskSweeper/downloads/OmniDiskSweeper-1.12.dmg',
           'download_changed': True,
           'items_to_copy': [{'destination_path': '/Applications/',
                              'source_item': 'OmniDiskSweeper.app'}]}}
InstallFromDMG: Mounted disk image /Users/allister/Library/AutoPkg/Cache/com.github.autopkg.install.OmniDiskSweeper/downloads/OmniDiskSweeper-1.12.dmg
InstallFromDMG: Connecting
InstallFromDMG: Sending installation request
InstallFromDMG: STATUS:Copying OmniDiskSweeper.app to /Applications/OmniDiskSweeper.app
InstallFromDMG: Disconnecting
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/InstallFromDMG.py", line 149, in main
    self.install()
  File "/Library/AutoPkg/autopkglib/InstallFromDMG.py", line 96, in install
    self.disconnect()
  File "/Library/AutoPkg/autopkglib/InstallFromDMG.py", line 145, in disconnect
    self.socket.close()
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/socket.py", line 420, in close
    self._real_close()
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/socket.py", line 414, in _real_close
    _ss.close(self)
OSError: [Errno 9] Bad file descriptor
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
[Errno 9] Bad file descriptor
Failed.
```

10.14.6
AutoPkg Version 2.0b3

**Comment by nmcspadden** [comment]
Fixed in 7e08b6e1a7b7c4f613c9e710700529832f2a5c04.
