### ISSUE TITLE
2.0RC1 | SparkleUpdateInfoProvider has variable type issue with one feed

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#594]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
SparkleUpdateInfoProvider, while mostly working with Sparkle feeds, fails with the feed at https://sparkle.boinx.com/appcast.lasso, when it tries to compare a `str` and `int`.

**Preferences contents**
{
    "FAIL_RECIPES_WITHOUT_TRUST_INFO" = 1;
    "GIT_PATH" = "/usr/local/git/bin/git";
[…]}

**AutoPkg output**
```
autopkg run -vv iStopMotion3.download
Processing iStopMotion3.download...
SparkleUpdateInfoProvider
{'Input': {'appcast_query_pairs': {'appID': 'ISTO',
                                   'appName': 'iStopMotion',
                                   'feedtype': '1',
                                   'lang': 'en',
                                   'locale': 'en_US',
                                   'versionString': '3.0'},
           'appcast_request_headers': {'User-Agent': 'curl/7.43.0'},
           'appcast_url': 'https://sparkle.boinx.com/appcast.lasso'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/SparkleUpdateInfoProvider.py", line 304, in main
    sorted_items = sorted(items, key=lambda a: LooseVersion(a["version"]))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
'<' not supported between instances of 'str' and 'int'
Failed.
Receipt written to /Users/tech/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/receipts/iStopMotion3-receipt-20191209-085008.plist

The following recipes failed:
    iStopMotion3.download
        Error in com.github.timsutton.download.iStopMotion: Processor: SparkleUpdateInfoProvider: Error: '<' not supported between instances of 'str' and 'int'

Nothing downloaded, packaged or imported.
```
**Expected behaviour**
Sparkle feed will be processed correctly as in AutoPkg 1.4.

**Version:**
 - OS version: 10.15.1
- AutoPkg Version: 2.0RC1

**Comment by MichalMMac** [comment]
Code in `distutils/version.py` crashed when comparing two arrays:

```
 [3, 8, '-', 16051, 'app'] < [3, 8, 1, '-', 16053, 'app'] 
```

**Comment by gregneagle** [comment]
Yikes.
```$ python3
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils import version
>>> version.LooseVersion("3.8-16051") == version.LooseVersion("3.8.1-16053")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Shared/code/relocatable-python/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 46, in __eq__
    c = self._cmp(other)
  File "/Users/Shared/code/relocatable-python/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'```

This is likely to affect Munki I'd think as well

**Comment by gregneagle** [comment]
Interestingly, Munki's subclass of LooseVersion handles this OK (at least without crashing):

```
$ python3
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from munkilib.pkgutils import MunkiLooseVersion
>>> MunkiLooseVersion("3.8-16051") == MunkiLooseVersion("3.8.1-16053")
False
```

of course the ordering is not what a human might expect, but that's a known issue:

```
>>> MunkiLooseVersion("3.8-16051") < MunkiLooseVersion("3.8.1-16053")
False
>>> MunkiLooseVersion("3.8-16051") > MunkiLooseVersion("3.8.1-16053")
True
```

**Comment by MichalMMac** [comment]
Do you thing we should create autopkgs own LooseVersion subclass?

Are there any alternartives to `LooseVersion`? `LegacyVersion` from `packaging.version` perhaps?

**Comment by gregneagle** [comment]
There are alternatives, but all have slightly different behaviors when comparing version "numbers" that contain things other than digits and periods. Switching to a different library brings the risk of changing the behaviors of current functioning recipes.

**Comment by gregneagle** [comment]
Amusing:

https://github.com/munki/munki/blob/master/code/client/munkilib/pkgutils.py#L122-L124

I evidently found that distutils.version.LooseVersion was broken and fixed it for Munki's use and then promptly forgot about it...

**Comment by nmcspadden** [comment]
This is fixed in commit https://github.com/autopkg/autopkg/commit/7c0676fdfe77f66f261b0df53ec5a792d31c5d3c, thanks to @gregneagle for porting over a LooseVersion replacement from Munki.

```
$ ./autopkg run -vvvv iStopMotion3.download                                                                                          
Processing iStopMotion3.download...
WARNING: iStopMotion3.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.0.1',
 'NAME': 'iStopMotion',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion',
 'RECIPE_DIR': '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes/Boinx',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes/Boinx/iStopMotion3.download.recipe',
 'RECIPE_REPOS': {'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'},
                  '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes': {'URL': 'https://github.com/autopkg/timsutton-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'],
 'verbose': 4}
SparkleUpdateInfoProvider
{'Input': {'appcast_query_pairs': {'appID': 'ISTO',
                                   'appName': 'iStopMotion',
                                   'feedtype': '1',
                                   'lang': 'en',
                                   'locale': 'en_US',
                                   'versionString': '3.0'},
           'appcast_request_headers': {'User-Agent': 'curl/7.43.0'},
           'appcast_url': 'https://sparkle.boinx.com/appcast.lasso'}}
SparkleUpdateInfoProvider: Curl command: ['/usr/bin/curl', '--compressed', '--location', '--header', 'User-Agent: curl/7.43.0', 'https://sparkle.boinx.com/appcast.lasso?appName=iStopMotion&lang=en&appID=ISTO&versionString=3.0&locale=en_US&feedtype=1']
SparkleUpdateInfoProvider: Version retrieved from appcast: 3.8-16051.app
SparkleUpdateInfoProvider: Found URL https://cdn.boinx.com/software/istopmotion/Boinx_iStopMotion_3.8-16051.app.zip
{'Output': {'url': 'https://cdn.boinx.com/software/istopmotion/Boinx_iStopMotion_3.8-16051.app.zip',
            'version': '3.8-16051.app'}}
URLDownloader
{'Input': {'request_headers': {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel '
                                             'Mac OS X 10_10_1) '
                                             'AppleWebKit/537.36 (KHTML, like '
                                             'Gecko) Chrome/39.0.2171.95 '
                                             'Safari/537.36'},
           'url': 'https://cdn.boinx.com/software/istopmotion/Boinx_iStopMotion_3.8-16051.app.zip'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Curl command: ['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://cdn.boinx.com/software/istopmotion/Boinx_iStopMotion_3.8-16051.app.zip', '--fail', '--output', '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/tmp23vvclyb', '--header', 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36']
URLDownloader: Storing new Last-Modified header: Sat, 14 May 2016 14:45:01 GMT
URLDownloader: Storing new ETag header: "2ab237a-532ce6fa2b3a0"
URLDownloader: Downloaded /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip
{'Output': {'download_changed': True,
            'etag': '"2ab237a-532ce6fa2b3a0"',
            'last_modified': 'Sat, 14 May 2016 14:45:01 GMT',
            'pathname': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
Unarchiver
{'Input': {'archive_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip',
           'destination_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion',
           'purge_destination': True}}
Unarchiver: Guessed archive format 'zip' from filename Boinx_iStopMotion_3.8-16051.app.zip
Unarchiver: Unarchived /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip to /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/*.app',
           'requirement': 'identifier "com.boinx.iStopMotion3" and anchor '
                          'apple generic and certificate '
                          '1[field.1.2.840.113635.100.6.2.6] /* exists */ and '
                          'certificate leaf[field.1.2.840.113635.100.6.1.13] '
                          '/* exists */ and certificate leaf[subject.OU] = '
                          '"6372P8EH2J"'}}
CodeSignatureVerifier: Using path '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/iStopMotion.app' matched from globbed '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/*.app'.
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/iStopMotion.app: valid on disk
CodeSignatureVerifier: /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/iStopMotion.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/iStopMotion.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
{'AUTOPKG_VERSION': '2.0.1',
 'CHECK_FILESIZE_ONLY': False,
 'NAME': 'iStopMotion',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion',
 'RECIPE_DIR': '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes/Boinx',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes/Boinx/iStopMotion3.download.recipe',
 'RECIPE_REPOS': {'/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'},
                  '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes': {'URL': 'https://github.com/autopkg/timsutton-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes',
                        '/Users/nmcspadden/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'],
 'additional_pkginfo': {},
 'appcast_query_pairs': {'appID': 'ISTO',
                         'appName': 'iStopMotion',
                         'feedtype': '1',
                         'lang': 'en',
                         'locale': 'en_US',
                         'versionString': '3.0'},
 'appcast_request_headers': {'User-Agent': 'curl/7.43.0'},
 'appcast_url': 'https://sparkle.boinx.com/appcast.lasso',
 'archive_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip',
 'destination_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion',
 'download_changed': True,
 'etag': '"2ab237a-532ce6fa2b3a0"',
 'input_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/iStopMotion/*.app',
 'last_modified': 'Sat, 14 May 2016 14:45:01 GMT',
 'pathname': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip',
 'prefetch_filename': False,
 'purge_destination': True,
 'request_headers': {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                   '10_10_1) AppleWebKit/537.36 (KHTML, like '
                                   'Gecko) Chrome/39.0.2171.95 Safari/537.36'},
 'requirement': 'identifier "com.boinx.iStopMotion3" and anchor apple generic '
                'and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists '
                '*/ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* '
                'exists */ and certificate leaf[subject.OU] = "6372P8EH2J"',
 'url': 'https://cdn.boinx.com/software/istopmotion/Boinx_iStopMotion_3.8-16051.app.zip',
 'url_downloader_summary_result': {'data': {'download_path': '/Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip'},
                                   'summary_text': 'The following new items '
                                                   'were downloaded:'},
 'verbose': 4,
 'version': '3.8-16051.app'}
Receipt written to /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/receipts/iStopMotion3-receipt-20191217-145925.plist

The following new items were downloaded:
    Download Path                                                                                                                    
    -------------                                                                                                                    
    /Users/nmcspadden/Library/AutoPkg/Cache/com.github.timsutton.download.iStopMotion/downloads/Boinx_iStopMotion_3.8-16051.app.zip  
```

I've also tested this with Handbrake.download, which also uses GitHubReleasesInfoProvider.

**Comment by nmcspadden** [comment]
The commit is only in the dev branch for now, so please test it to confirm it's not just me, and I'll merge it in to master at some point.

**Comment by homebysix** [comment]
I've tested the iStopMotion on 7c0676f successfully.

I also ran 7c0676f on all my download recipes that contain SparkleUpdateInfoProvider or GitHubReleasesInfoProvider, and encountered no unexpected issues, only expected ones.
