### ISSUE TITLE
URLGetter doesn't produce human-understandable output upon HTTP errors

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#607]
The output generated by a 404, 503, or other common server-side errors is difficult to understand.

In the example below, the URL that URLDownloader is attempting to download (https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg) currently results in a 404. But rather than saying so, AutoPkg returns `returned non-zero exit status 22` and full traceback output.

**AutoPkg output**

```
% autopkg run -vvcq LaunchBar5.download.recipe
Processing LaunchBar5.download.recipe...
WARNING: LaunchBar5.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
LaunchBar5URLProvider
{'Input': {}}
LaunchBar5URLProvider: Fetching update feed data from URL https://sw-update.obdev.at/update-feeds/launchbar-5.plist
LaunchBar5URLProvider: Found update feed data.
LaunchBar5URLProvider: Found URL https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg
LaunchBar5URLProvider: Found version 6.9
LaunchBar5URLProvider: Found download filename LaunchBar-6.9.dmg
{'Output': {'filename': 'LaunchBar-6.9.dmg',
            'url': 'https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg',
            'version': '6.9'}}
URLDownloader
{'Input': {'filename': 'LaunchBar-6.9.dmg',
           'url': 'https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 189, in execute_curl
    text=text,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.jaharmi.download.LaunchBar5/downloads/tmp0qpu0uo8']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 316, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 197, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 192, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.jaharmi.download.LaunchBar5/downloads/tmp0qpu0uo8']' returned non-zero exit status 22.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.jaharmi.download.LaunchBar5/downloads/tmp0qpu0uo8']' returned non-zero exit status 22.
Failed.
Receipt written to ~/Library/AutoPkg/Cache/com.github.jaharmi.download.LaunchBar5/receipts/LaunchBar5.download-receipt-20200119-175519.plist

The following recipes failed:
    LaunchBar5.download.recipe
        Error in com.github.jaharmi.download.LaunchBar5: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://sw-update.obdev.at/ftp/pub/Products/LaunchBar/LaunchBar-6.9.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.jaharmi.download.LaunchBar5/downloads/tmp0qpu0uo8']' returned non-zero exit status 22.

Nothing downloaded, packaged or imported.
```

**Expected behavior**

For common HTTP errors, processors based on URLGetter should return the number of the error, as these are better understood by Mac admins than curl exit codes.

**Version:**

 - OS version: 10.15.2
- AutoPkg Version: 2.0rc1

**Comment by MichalMMac** [comment]
I see the problem. 

[Change](https://github.com/autopkg/autopkg/commit/facad8ce48cfb9766578d55823660feb177b3e80) from `subprocess.Popen()` to `subprocess.run()` introduced this. `check=True` in `subprocess.run()` causes exception to be raised for all non zero exit codes.

There are two `retcode` checks. One in URLGetter and one in github module which should produce human readable exception text. However they are never triggered since `result.returncode` returned from `execute_curl()` is always zero.

I see two possible solutions:

- Revert the changes introduced in commit facad8ce48cfb9766578d55823660feb177b3e80
- Handle the error text in the `execute_curl()` except: block. It might be as simple as https://github.com/MichalMMac/autopkg/commit/6e041eac512dfac17472bafea623e071d0846828 We need to be sure this is want we want for all situations. It should be fine for `download_with_curl` https://github.com/autopkg/autopkg/blob/6b8914be1b5cd9c1da793a3a77125e30bddaa8c5/Code/autopkglib/URLGetter.py#L199 but I haven studied the ouput handling in https://github.com/autopkg/autopkg/blob/6b8914be1b5cd9c1da793a3a77125e30bddaa8c5/Code/autopkglib/github/__init__.py#L138 Additionally code in these two places should be eliminated since it's never used. 

@nmcspadden Could you take a look?

**Comment by nmcspadden** [comment]
Hmm, looking at it again, I don't think `execute_curl()` should have `check=True`; we should instead let upstream consumers of this function do their own error handling instead of automatically failing if curl ever exits non-zero (i.e. due to a 404, which is something I hadn't really anticipated but makes sense).

**Comment by MichalMMac** [comment]
What about the alternatives?

Maybe add option to disable the check for the 3rd party code?

```def execute_curl(self, curl_cmd, text=True, check=True)```

+ In autopkg core code we might be able to handle the error with the exception and simplify the code.

# URLGetter

Error handling in URLGetter itself can be probably done with the exception (check=True) and my fix https://github.com/MichalMMac/autopkg/commit/6e041eac512dfac17472bafea623e071d0846828. Compare:

## Exception handling (check=True)

```
Processing DEVRemote.download...
URLDownloader
curl: (22) The requested URL returned error: 404 Not Found

Failed.

The following recipes failed:
    DEVRemote.download
        Error in com.github.michalmmac.DEVRemote: Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 404 Not Found

Nothing downloaded, packaged or imported.
```

## Original handling (check=False)

```
Processing DEVRemote.download...
URLDownloader
curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.

The following recipes failed:
    DEVRemote.download
        Error in com.github.michalmmac.DEVRemote: Processor: URLDownloader: Error: curl failure: The requested URL returned error: 404 Not Found (exit code 22)

Nothing downloaded, packaged or imported.
```

# GitHubSession

This is much more difficult. As far as I know this module i designed to return data **and HTTP return code**. 

Error handling code here is a bit complicated. We could **simplify it**. Rely on `curl --fail` and following exception. Would not return the HTTP return code. This would be probably OK for `GitHubReleasesInfoProvider`: https://github.com/autopkg/autopkg/blob/6b8914be1b5cd9c1da793a3a77125e30bddaa8c5/Code/autopkglib/GitHubReleasesInfoProvider.py#L98 but `autopkg` checks for 403 to inform user about the rate limit. https://github.com/autopkg/autopkg/blob/6b8914be1b5cd9c1da793a3a77125e30bddaa8c5/Code/autopkg#L892 



Error handling in GitHubReleasesInfoProvider->GitHubSession and my fix https://github.com/MichalMMac/autopkg/commit/6e041eac512dfac17472bafea623e071d0846828. Compare:

## Exception handling (check=True)

```
Processing GithubDWN.download...
GitHubReleasesInfoProvider
curl: (22) The requested URL returned error: 404 Not Found

Failed.

The following recipes failed:
    GithubDWN.download
        Error in com.github.michalmmac.GithubDWN: Processor: GitHubReleasesInfoProvider: Error: curl: (22) The requested URL returned error: 404 Not Found
```

## Original handling (check=False)

```
Processing GithubDWN.download...
GitHubReleasesInfoProvider
Curl failure: Could not retrieve URL https://api.github.com/repos/MacPassdrak/MacPass/releases: The requested URL returned error: 404 Not Found
[Errno 2] No such file or directory: '/var/folders/mn/2d9212bd4_n3clfx6qnb6_wm0000gp/T/tmp66_juooe'
Failed.

The following recipes failed:
    GithubDWN.download
        Error in com.github.michalmmac.GithubDWN: Processor: GitHubReleasesInfoProvider: Error: [Errno 2] No such file or directory: '/var/folders/mn/2d9212bd4_n3clfx6qnb6_wm0000gp/T/tmp66_juooe'
```
