### ISSUE TITLE
Traceback in output when raising ProcessorError in AutoPkg 2.0rc1

### ISSUE THREAD

**Issue by homebysix** [autopkg/autopkg#608]
**Describe the problem**
A Python traceback appears in the output of AutoPkg when a processor raises a ProcessorError, no matter the verbosity level. This may cause admins who use AutoPkg but aren't familiar with Python to troubleshoot the wrong issue.

**Preferences contents**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>GIT_PATH</key>
	<string>/usr/local/bin/git</string>
	<key>RECIPE_OVERRIDE_DIRS</key>
	<array>
		<string>~/Library/AutoPkg/RecipeOverrides</string>
	</array>
	<key>RECIPE_REPOS</key>
	<dict>
		<key>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes</key>
		<dict>
			<key>URL</key>
			<string>https://github.com/autopkg/homebysix-recipes</string>
		</dict>
		<key>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes</key>
		<dict>
			<key>URL</key>
			<string>https://github.com/autopkg/jleggat-recipes</string>
		</dict>
	</dict>
	<key>RECIPE_SEARCH_DIRS</key>
	<array>
		<string>.</string>
		<string>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes</string>
		<string>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes</string>
	</array>
</dict>
</plist>
```

**Steps to reproduce**

1. Get info on an example recipe.

```% autopkg info Fetch/Fetch.download.recipe
Description:         Download recipe for Fetch.  Downloads the latest Fetch from Fetch Softworks website.
Identifier:          com.github.jleggat.download.Fetch
Munki import recipe: False
Has check phase:     True
Builds package:      False
Recipe file path:    Fetch/Fetch.download.recipe
Input values: 
    'NAME': 'Fetch',
    'SEARCH_PATTERN': '(?P<url>fetch/download/Fetch_(?P<version>[0-9.]+)\\.zip)',
    'SEARCH_URL': 'https://fetchsoftworks.com'
```

2. Run the example recipe so that it succeeds.

```
% autopkg run -vvcq  Fetch/Fetch.download.recipe
Processing Fetch/Fetch.download.recipe...
WARNING: Fetch/Fetch.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(?P<url>fetch/download/Fetch_(?P<version>[0-9.]+)\\.zip)',
           'url': 'https://fetchsoftworks.com'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (url): fetch/download/Fetch_5.8.zip
URLTextSearcher: Found matching text (version): 5.8
URLTextSearcher: Found matching text (match): fetch/download/Fetch_5.8.zip
{'Output': {'match': 'fetch/download/Fetch_5.8.zip',
            'url': 'fetch/download/Fetch_5.8.zip',
            'version': '5.8'}}
URLDownloader
{'Input': {'filename': 'Fetch-5.8.zip',
           'url': 'https://fetchsoftworks.com/fetch/download/Fetch_5.8.zip?direct=1'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing ~/Library/AutoPkg/Cache/com.github.jleggat.download.Fetch/downloads/Fetch-5.8.zip
{'Output': {'pathname': '~/Library/AutoPkg/Cache/com.github.jleggat.download.Fetch/downloads/Fetch-5.8.zip'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
Receipt written to ~/Library/AutoPkg/Cache/com.github.jleggat.download.Fetch/receipts/Fetch.download-receipt-20200120-225707.plist

Nothing downloaded, packaged or imported.
```

3. Run the example recipe so that it raises a ProcessorError.

```
% autopkg run -vvcq Fetch/Fetch.download.recipe -k SEARCH_URL="https://fetchsoftworks.com/boguspath"
Processing Fetch/Fetch.download.recipe...
WARNING: Fetch/Fetch.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(?P<url>fetch/download/Fetch_(?P<version>[0-9.]+)\\.zip)',
           'url': 'https://fetchsoftworks.com/boguspath'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 114, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 101, in re_search
    raise ProcessorError(f"No match found on URL: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://fetchsoftworks.com/boguspath
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
No match found on URL: https://fetchsoftworks.com/boguspath
Failed.
Receipt written to ~/Library/AutoPkg/Cache/com.github.jleggat.download.Fetch/receipts/Fetch.download-receipt-20200120-225747.plist

The following recipes failed:
    Fetch/Fetch.download.recipe
        Error in com.github.jleggat.download.Fetch: Processor: URLTextSearcher: Error: No match found on URL: https://fetchsoftworks.com/boguspath

Nothing downloaded, packaged or imported.
```

To verify: this issue is not limited to recipes that use URLTextSearcher. Here's another traceback from a recipe that uses URLDownloader:

```
URLDownloader
{'Input': {'filename': 'FileChute.dmg',
           'url': 'https://www.yellowmug.com/download/FileChute.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 189, in execute_curl
    text=text,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://www.yellowmug.com/download/FileChute.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.homebysix.download.FileChute/downloads/tmpd9pbxpim']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 316, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 197, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 192, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://www.yellowmug.com/download/FileChute.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.homebysix.download.FileChute/downloads/tmpd9pbxpim']' returned non-zero exit status 22.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://www.yellowmug.com/download/FileChute.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.homebysix.download.FileChute/downloads/tmpd9pbxpim']' returned non-zero exit status 22.
Failed.
Receipt written to ~/Library/AutoPkg/Cache/com.github.homebysix.download.FileChute/receipts/FileChute.download-receipt-20200120-231413.plist

The following recipes failed:
    YellowMug/FileChute.download.recipe
        Error in com.github.homebysix.download.FileChute: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://www.yellowmug.com/download/FileChute.dmg', '--fail', '--output', '~/Library/AutoPkg/Cache/com.github.homebysix.download.FileChute/downloads/tmpd9pbxpim']' returned non-zero exit status 22.
```

**Expected behavior**

The expected behavior is what AutoPkg 1.4.1 does: a ProcessorError generates concise output without additional Python tracebacks.

```
% autopkg run -vvcq Fetch/Fetch.download.recipe -k SEARCH_URL="https://fetchsoftworks.com/boguspath"
Processing Fetch/Fetch.download.recipe...
WARNING: Fetch/Fetch.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': u'(?P<url>fetch/download/Fetch_(?P<version>[0-9.]+)\\.zip)',
           'url': u'https://fetchsoftworks.com/boguspath'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
No match found on URL: https://fetchsoftworks.com/boguspath
Failed.
Receipt written to ~/Library/AutoPkg/Cache/com.github.jleggat.download.Fetch/receipts/Fetch.download-receipt-20200120-225845.plist

The following recipes failed:
    Fetch/Fetch.download.recipe
        Error in com.github.jleggat.download.Fetch: Processor: URLTextSearcher: Error: No match found on URL: https://fetchsoftworks.com/boguspath

Nothing downloaded, packaged or imported.
```

**Version (please complete the following information):**
 - OS version: 10.15.2
- AutoPkg Version: 2.0rc1

**Comment by homebysix** [comment]
I see this may be intended behavior: https://github.com/autopkg/autopkg/commit/e1e7fa30dd0e09130a0fc7f38e40013199b3d763

However, I'd petition to have the tracebacks present in a higher verbosity level only, because it's a pretty noticeable change in the `-v` and `-vv` outputs.

**Comment by gregneagle** [comment]
I tend to agree here. It's useful to have access to the additional information from the full tracebacks, but perhaps not at the default verbosity level.
