### ISSUE TITLE
Installer processor fails when closing socket 

### ISSUE THREAD

**Issue by nstrauss** [autopkg/autopkg#615]
**Describe the problem**
Sometimes Installer fails due to attempting to closing a socket that's already closed. Behavior changed in Python 3 to automatically close.  

**AutoPkg output**
```
Installer: STATUS:installer: The upgrade was successful.
Installer: Disconnecting
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/Installer.py", line 181, in main
    self.install()
  File "/Library/AutoPkg/autopkglib/Installer.py", line 127, in install
    self.disconnect()
  File "/Library/AutoPkg/autopkglib/Installer.py", line 177, in disconnect
    self.socket.close()
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/socket.py", line 420, in close
    self._real_close()
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/socket.py", line 414, in _real_close
    _ss.close(self)
OSError: [Errno 9] Bad file descriptor
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
[Errno 9] Bad file descriptor
Failed.
```

**Expected behavior**
Processor complete without error. 

**Version (please complete the following information):**
 - OS version: 10.14.6, 10.15.2
- AutoPkg Version: 2.0.2

Kind of a band aid fix, but I am able to get it working by changing code starting at line 125...

```
finally:
    self.output("Disconnecting")
    try:
        self.disconnect()
    except OSError:
        pass
```

**Comment by nmcspadden** [comment]
Fixed in https://github.com/autopkg/autopkg/commit/09a5f5c2d6f5aaa9dd2963b722ced6f4915b60f1. Please test and confirm, but re-open if this doesn't work. I'll merge it into master after some experimenting.
