### ISSUE TITLE
python Syntax Error

### ISSUE THREAD

**Issue by msanchezwhs** [autopkg/autopkg#635]
`Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2887, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2881, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2397, in run_recipes
    autopackager.verify(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 599, in verify
    step["Processor"], verbose=self.verbose, recipe=recipe, env=self.env
  File "/Library/AutoPkg/autopkglib/__init__.py", line 894, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/AdobeFlashPlayer/AdobeFlashURLProvider.py", line 95
    except (OSError, IOError, ElementTree.ParseError), err:
                                                     ^
SyntaxError: invalid syntax 
`

**Comment by gregneagle** [comment]
Guessing you closed this as it was caused by an out-of-date recipes repo, and was fixed with an `autopkg repo-update recipes`...
