### ISSUE TITLE
Status code of 22 when getting info of recipe with escaped spaces

### ISSUE THREAD

**Issue by ewancolyer** [autopkg/autopkg#643]
**Describe the problem**
When I search `autopkg info Google\ Chrome.munki` I get this returned to me 
```munki-repo ewan.colyer$ autopkg info Google\ Chrome.munki
Didn't find a recipe for Google Chrome.munki.
Maybe you meant one of: GoogleChrome.munki, GoogleChat.munki, GoogleChromePkg.munki?
Search GitHub AutoPkg repos for a Google Chrome.munki recipe? [y/n]: y
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 191, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3.text-match+json', '--url', 'https://api.github.com/search/code?q=Google Chrome.munki+extension:recipe+user:autopkg+in:file,path&per_page=100', '--output', '/var/folders/vv/_6vf44ks5bsf1zt1twz4ffbm0000gp/T/tmpp6qcns3b']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2887, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2881, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 1154, in get_info
    auto_pull=options.pull,
  File "/usr/local/bin/autopkg", line 511, in get_recipe_info
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 400, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 333, in locate_recipe
    results_items = search_gh_for_name(name)
  File "/usr/local/bin/autopkg", line 238, in search_gh_for_name
    results = do_gh_code_search(query, use_token=False)
  File "/usr/local/bin/autopkg", line 960, in do_gh_code_search
    "/search/code", query=query, accept="application/vnd.github.v3.text-match+json"
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 186, in call_api
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 136, in download_with_curl
    p_stdout, p_stderr, retcode = self.execute_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 194, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3.text-match+json', '--url', 'https://api.github.com/search/code?q=Google Chrome.munki+extension:recipe+user:autopkg+in:file,path&per_page=100', '--output', '/var/folders/vv/_6vf44ks5bsf1zt1twz4ffbm0000gp/T/tmpp6qcns3b']' returned non-zero exit status 22.
```

When I search `GoogleChrome.munki` it searches fine, this behaviour seems to be replicated for any recipes that have spaces in the name that you escape, if you curl the above url, it reports it as an illegal command, if you then take the space out from between `Google` and `Chrome` it returns the expected result.

@grahampugh also reported similar issues on friday, im not sure whether those recipes also had spaces in or not?

**Preferences contents**
```{
    "RECIPE_REPOS" =     {
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes" =         {
            URL = "https://github.com/autopkg/apettinen-recipes";
        };
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.chilcote-recipes" =         {
            URL = "https://github.com/autopkg/chilcote-recipes";
        };
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes" =         {
            URL = "https://github.com/autopkg/homebysix-recipes";
        };
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes";
        };
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes" =         {
            URL = "https://github.com/autopkg/sheagcraig-recipes";
        };
    };
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes",
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.chilcote-recipes",
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes",
        "/Users/ewan.colyer/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes"
    );
}
```

**Version (please complete the following information):**
 - OS version: 10.15.4
- AutoPkg Version: 2.1

**Comment by nmcspadden** [comment]
Looks like the recipe name is not being properly urlquoted when being passed in to the github search. Relatively easy fix, though.

I'm starting to think more and more I should actively prevent spaces in recipe names.

**Comment by ewancolyer** [comment]
> Looks like the recipe name is not being properly urlquoted when being passed in to the github search. Relatively easy fix, though.
> 
> I'm starting to think more and more I should actively prevent spaces in recipe names.

I don't see why there is a need to have spaces in recipe names, and I've not come across that many that have them!

**Comment by macmule** [comment]
@ewancolyer our repo is full of recipes with spaces in the name...

**Comment by nmcspadden** [comment]
I can't repro this on either dev or master branch anymore:
```
$ ./autopkg info Google\ Chrome.munki
Didn't find a recipe for Google Chrome.munki.
Maybe you meant one of: GoogleChromeCanary.munki, GoogleChromePkg.munki, GoogleChrome.munki?
Search GitHub AutoPkg repos for a Google Chrome.munki recipe? [y/n]: y

Name                                     Repo                      Path                                    
----                                     ----                      ----                                    
ChromeRemoteDesktop.munki.recipe         apizz-recipes             Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe
GoogleChromeCanary.munki.recipe          foigus-recipes            Google/GoogleChromeCanary.munki.recipe  
GoogleChromeEnterprise.munki.recipe      grahamgilbert-recipes     Google/GoogleChromeEnterprise.munki.recipe
CitrixReceiver.munki.recipe              jessepeterson-recipes     CitrixReceiver/CitrixReceiver.munki.recipe
GoogleChromePkg.munki.recipe             recipes                   GoogleChrome/GoogleChromePkg.munki.recipe
GoogleChrome.munki.recipe                recipes                   GoogleChrome/GoogleChrome.munki.recipe  
MSOffice2011Updates.munki.recipe         recipes                   MSOffice2011Updates/MSOffice2011Updates.munki.recipe
Office2011Updates-fr_FR.munki.recipe     ygini-recipes             MSOfficeUpdates/Office2011Updates-fr_FR.munki.recipe
ChromeRemoteDesktop.munki.recipe         zentral-recipes           Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe

To add a new recipe repo, use 'autopkg repo-add <repo name>'
No valid recipe found for Google Chrome.munki

$ ./autopkg info Microsoft\ Word\ 2019.munki
Didn't find a recipe for Microsoft Word 2019.munki.
Maybe you meant one of: MSWord2019.munki, MicrosoftWord365.munki, MicrosoftEdge.munki?
Search GitHub AutoPkg repos for a Microsoft Word 2019.munki recipe? [y/n]: y

Name                                                      Repo                        Path                                    
----                                                      ----                        ----                                    
Microsoft Word 2019.munki.recipe                          dataJAR-recipes             Microsoft Word 2019/Microsoft Word 2019.munki.recipe
MicrosoftMacProductFWLink.download.recipe                 jazzace-recipes             Microsoft/MicrosoftMacProductFWLink.download.recipe
Mendeley.munki.recipe                                     joshua-d-miller-recipes     Mendeley/Mendeley.munki.recipe          
MSWord2019.munki.recipe                                   recipes                     MSOfficeUpdates/MSWord2019.munki.recipe 
Office2019SuiteSKUless_additionalpkginfo.munki.recipe     wardsparadox-recipes        Forked Recipes/Office2019SuiteSKUless_additionalpkginfo.munki.recipe

To add a new recipe repo, use 'autopkg repo-add <repo name>'
No valid recipe found for Microsoft Word 2019.munki
```

Looks like this got fixed as a result of some of the other improvements. If you can find a new repro-case, please re-open the issue with new information.
