### ISSUE TITLE
PkgCreator fails if cache is on external drive

### ISSUE THREAD

**Issue by SmithersJr** [autopkg/autopkg#677]
**Describe the problem**
This seems to be similar to problem #34. 

GoogleChrome.pkg runs correctly when the cache is set to the default directory. But, not when the cache is set for an external drive. My internal drive is not very large; so, I am trying to setup AutoPkg to store the cache on an external drive with ownership enabled.

(FYI: Firefox.pkg produces a similar error. AdobeFlashPlayer.pkg works correctly, presumably because of this: "No repackaging done.")

Error:
```
The following recipes failed:
    GoogleChrome.pkg
        Error in com.github.autopkg.pkg.googlechrome: Processor: PkgCreator: Error: Couldn't copy pkgroot from /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome to /tmp/tmpb9y7o897/GoogleChrome: ditto: /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/.: Operation not permitted

The following new items were downloaded:
    Download Path                                                                         
    -------------                                                                         
    /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg  
```
 Per the thread in the previous ticket, I have ensured `GlobalPermissionsEnabled` is on and rebooted and recreated the cache folder.
```
	<key>GlobalPermissionsEnabled</key>
	<true/>
```
My "autopkguser" account (non-admin) is the owner of `/Volumes/Data/AutoPkg` with R/W permissions…
```
autopkguser@Mac-mini ~ % ls -l /Volumes/Data/ 
total 0
drwxr-xr-x    4 autopkguser  wheel   128 Sep  9 10:06 AutoPkg
drwxrwxr-x   51 503          staff  1632 Jul 16 14:51 AutoPkg Cache backup
drwxr-xr-x@ 168 autopkguser  staff  5376 Sep  8 13:18 Content Cache
drwxr-xr-x    6 autopkguser  staff   192 Jul 30 16:15 Downloads
```
…as well as the folders for this particular recipe.
```
autopkguser@Mac-mini ~ % ls -l /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome
total 0
drwxr-xr-x  3 autopkguser  wheel  96 Sep  9 10:06 GoogleChrome
drwxr-xr-x  3 autopkguser  wheel  96 Sep  9 10:06 downloads
drwxr-xr-x  3 autopkguser  wheel  96 Sep  9 10:06 receipts
```
**Preferences contents**
```
{
    "API_PASSWORD" = XXX;
    "API_USERNAME" = YYY;
    "CACHE_DIR" = "/Volumes/Data/AutoPkg";
    "GIT_PATH" = "/usr/local/git/bin/git";
    "JSS_REPOS" =     (
                {
            type = CDP;
        }
    );
    "JSS_URL" = "ZZZ";
    "JSS_VERIFY_SSL" = 1;
    "RECIPE_REPOS" =     {
        "/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes" =         {
            URL = "https://github.com/autopkg/jss-recipes.git";
        };
        "/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes.git";
        };
        "/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer" =         {
            URL = "https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git";
        };
    };
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer",
        "/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes",
        "/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes"
    );
}
```
**AutoPkg output**
```
autopkguser@Mac-mini ~ % autopkg run -vvvv GoogleChrome.pkg
Processing GoogleChrome.pkg...
WARNING: GoogleChrome.pkg is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'API_PASSWORD': ‘XXX’,
 'API_USERNAME': ‘YYY’,
 'AUTOPKG_VERSION': '2.2',
 'CACHE_DIR': '/Volumes/Data/AutoPkg',
 'DOWNLOAD_URL': 'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg',
 'GIT_PATH': '/usr/local/git/bin/git',
 'JSS_REPOS': [{'type': 'CDP'}],
 'JSS_URL': ‘ZZZ’,
 'JSS_VERIFY_SSL': True,
 'NAME': 'GoogleChrome',
 'PARENT_RECIPES': ['/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome/GoogleChrome.download.recipe'],
 'RECIPE_CACHE_DIR': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome',
 'RECIPE_DIR': '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome/GoogleChrome.pkg.recipe',
 'RECIPE_REPOS': {'/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes': {'URL': 'https://github.com/autopkg/jss-recipes.git'},
                  '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer': {'URL': 'https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer',
                        '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes',
                        '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/autopkguser/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/GoogleChrome'],
 'verbose': 4}
URLDownloader
{'Input': {'filename': 'GoogleChrome.dmg',
           'url': 'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Curl command: ['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg', '--fail', '--output', '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/tmpbbj06jai', '--header', 'If-None-Match: "6e06af"', '--header', 'If-Modified-Since: Sat, 05 Sep 2020 00:02:20 GMT']
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg
{'Output': {'pathname': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg/Google '
                         'Chrome.app',
           'requirement': '(identifier "com.google.Chrome" or identifier '
                          '"com.google.Chrome.beta" or identifier '
                          '"com.google.Chrome.dev" or identifier '
                          '"com.google.Chrome.canary") and (certificate leaf = '
                          'H"85cee8254216185620ddc8851c7a9fc4dfe120ef" or '
                          'certificate leaf = '
                          'H"c9a99324ca3fcb23dbcc36bd5fd4f9753305130a")',
           'strict_verification': False}}
CodeSignatureVerifier: Mounted disk image /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification disabled...
CodeSignatureVerifier: /private/tmp/dmg.LfWkYL/Google Chrome.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.LfWkYL/Google Chrome.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.LfWkYL/Google Chrome.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
{'Output': {}}
AppDmgVersioner
{'Input': {'dmg_path': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg'}}
AppDmgVersioner: Mounted disk image /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg
AppDmgVersioner: BundleID: com.google.Chrome
AppDmgVersioner: Version: 85.0.4183.102
{'Output': {'app_name': 'Google Chrome.app',
            'bundleid': 'com.google.Chrome',
            'version': '85.0.4183.102'}}
PkgRootCreator
{'Input': {'pkgdirs': {'Applications': '0775'},
           'pkgroot': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome'}}
PkgRootCreator: Created /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome
PkgRootCreator: Creating Applications
PkgRootCreator: Created /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/Applications
{'Output': {}}
Copier
{'Input': {'destination_path': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/Applications/Google '
                               'Chrome.app',
           'source_path': '/Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg/Google '
                          'Chrome.app'}}
Copier: Parsed dmg results: dmg_path: /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg, dmg: .dmg/, dmg_source_path: Google Chrome.app
Copier: Mounted disk image /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/downloads/GoogleChrome.dmg
Copier: Copied /private/tmp/dmg.XenyhR/Google Chrome.app to /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/Applications/Google Chrome.app
{'Output': {}}
PkgCreator
{'Input': {'pkg_request': {'chown': [{'group': 'admin',
                                      'path': 'Applications',
                                      'user': 'root'}],
                           'id': 'com.google.Chrome',
                           'options': 'purge_ds_store',
                           'pkgname': 'GoogleChrome-85.0.4183.102',
                           'version': '85.0.4183.102'}}}
PkgCreator: Connecting
PkgCreator: Sending packaging request
PkgCreator: Disconnecting
PkgCreator: Failed to close socket: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/PkgCreator.py", line 269, in main
    self.package()
  File "/Library/AutoPkg/autopkglib/PkgCreator.py", line 223, in package
    pkg_path = self.send_request(request)
  File "/Library/AutoPkg/autopkglib/PkgCreator.py", line 258, in send_request
    raise ProcessorError(", ".join([s.replace("ERROR:", "") for s in errors]))
autopkglib.ProcessorError: Couldn't copy pkgroot from /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome to /tmp/tmpmjvc_lbf/GoogleChrome: ditto: /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/.: Operation not permitted
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
Couldn't copy pkgroot from /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome to /tmp/tmpmjvc_lbf/GoogleChrome: ditto: /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/.: Operation not permitted
Failed.
Receipt written to /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/receipts/GoogleChrome-receipt-20200909-102306.plist

The following recipes failed:
    GoogleChrome.pkg
        Error in com.github.autopkg.pkg.googlechrome: Processor: PkgCreator: Error: Couldn't copy pkgroot from /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome to /tmp/tmpmjvc_lbf/GoogleChrome: ditto: /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome/.: Operation not permitted

Nothing downloaded, packaged or imported.
```
**Expected behavior**
I expected to receive a packaged installer for Chrome, similar to Flash:
```
The following packages were copied:
    Pkg Path                                                                                                
    --------                                                                                                
    /Volumes/Data/AutoPkg/com.github.autopkg.pkg.FlashPlayerExtractPackage/AdobeFlashPlayer-32.0.0.433.pkg  
```
**Version (please complete the following information):**
 - OS version: 10.15.6
- AutoPkg Version: 2.2 (just installed after Mac was wiped)

**Comment by gregneagle** [comment]
This is almost certainly caused by Catalina's privacy protections and there is nothing the autopkg developers can do about it.
You'll need to grant the appropriate permissions to access external drives.

**Comment by SmithersJr** [comment]
FYI: I switched my "autopkguser" account to an admin and rebooted. Unfortunately, I still got the same error.

**Comment by gregneagle** [comment]
Clues: 10.15.6, an external drive, and "Operation not permitted". All point toward privacy protections.

**Comment by SmithersJr** [comment]
Yeah, that makes sense. Grant which permissions to which application? Is this documented somewhere I can check?

**Comment by gregneagle** [comment]
I have no idea which things you'll need to grant the permissions to. At the very least, /Library/AutoPkg/autopkgserver/autopkgserver would need permissions to be able to access external drives, but since that's actually a Python _script_...

**Comment by nmcspadden** [comment]
If you find the answer, please comment it back here. At the very least, we can add a note about this in the Wiki.

**Comment by SmithersJr** [comment]
Looks good after granting Full Disk Access to “python3.7”. 👍 
```
The following packages were built:
    Identifier         Version        Pkg Path                                                                                  
    ----------         -------        --------                                                                                  
    com.google.Chrome  85.0.4183.102  /Volumes/Data/AutoPkg/com.github.autopkg.pkg.googlechrome/GoogleChrome-85.0.4183.102.pkg  
```
```
The following packages were built:
    Identifier               Version  Pkg Path                                                                    
    ----------               -------  --------                                                                    
    org.mozilla.firefox.pkg  80.0.1   /Volumes/Data/AutoPkg/com.github.autopkg.pkg.Firefox_EN/Firefox-80.0.1.pkg  
```

**Comment by gregneagle** [comment]
Only you can decide if you are happy with that solution -- I'd worry that other (possibly hostile) scripts that use Python now would have unintended access...

**Comment by SmithersJr** [comment]
Hmm, very good point. If I find that I can set that more granularly, I'll let you know.
