### ISSUE TITLE
Download URL with already-escaped character has the % of the escape sequence escaped, resulting in invalid URL

### ISSUE THREAD

**Issue by BioSehnsucht** [autopkg/autopkg#695]
**Describe the problem**
When trying to run the recipe com.github.homebysix.munki.Screens (found at  https://github.com/autopkg/homebysix-recipes/tree/master/Screens ), the current latest URL from the XML feed has a %20 (escaped space) in the URL, and the % gets escaped by AutoPkg and turned into %25, causing the resulting URL to be invalid and fail to download, with curl returning error code 22.

I am guessing it's the `SparkleUpdateInfoProvider` that's handling this wrong, since it's the first point the URL gets output in the verbose output and it's already wrong. Possibly `urlencode_path_component` needs to be set to `False`? Is there a method to override the download portion of the recipe? I only have done really basic overrides on the munki portion to set categories and such.

I tried adding the setting to the download recipe but then it complained that it different from expected when running my override ... so not sure how to configure this from an override?

**Preferences contents**
`defaults read com.github.autopkg`
```
{
    "GIT_PATH" = "/Library/Developer/CommandLineTools/usr/bin/git";
    "MUNKI_REPO" = "/Volumes/munki";
    "RECIPE_REPOS" =     {
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes" =         {
            URL = "https://github.com/autopkg/hansen-m-recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes" =         {
            URL = "https://github.com/autopkg/hjuutilainen-recipes.git";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes" =         {
            URL = "https://github.com/autopkg/homebysix-recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes" =         {
            URL = "https://github.com/autopkg/jleggat-recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes" =         {
            URL = "https://github.com/autopkg/killahquam-recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes" =         {
            URL = "https://github.com/autopkg/nmcspadden-recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rderewianko-recipes" =         {
            URL = "https://github.com/autopkg/rderewianko-recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes";
        };
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes" =         {
            URL = "https://github.com/autopkg/sheagcraig-recipes";
        };
    };
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rderewianko-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes",
        "/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes"
    );
}
```

**AutoPkg output**
```
$ autopkg run -vvvv local.munki.Screens
Processing local.munki.Screens...
{'AUTOPKG_VERSION': '2.2',
 'GIT_PATH': '/Library/Developer/CommandLineTools/usr/bin/git',
 'MUNKI_REPO': '/Volumes/munki',
 'MUNKI_REPO_SUBDIR': 'apps/Screens',
 'NAME': 'Screens',
 'PARENT_RECIPES': ['/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/Screens/Screens.munki.recipe',
                    '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/Screens/Screens.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/sysadmin/Library/AutoPkg/Cache/local.munki.Screens',
 'RECIPE_DIR': '/Users/sysadmin/Library/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/sysadmin/Library/AutoPkg/RecipeOverrides/Screens.munki.recipe',
 'RECIPE_REPOS': {'/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes.git'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes': {'URL': 'https://github.com/autopkg/jleggat-recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes': {'URL': 'https://github.com/autopkg/killahquam-recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes': {'URL': 'https://github.com/autopkg/nmcspadden-recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rderewianko-recipes': {'URL': 'https://github.com/autopkg/rderewianko-recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes': {'URL': 'https://github.com/autopkg/sheagcraig-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.sheagcraig-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rderewianko-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/sysadmin/Library/AutoPkg/RecipeOverrides',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/Screens',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/Screens',
                        '/Users/sysadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes/Screens'],
 'SPARKLE_FEED_URL': 'https://updates.edovia.com/com.edovia.screens4.mac/appcast.xml',
 'pkginfo': {'catalogs': ['testing'],
             'category': 'Remote Access',
             'description': 'VNC client app that allows you to view and/or '
                            'control a Mac remotely.',
             'developer': 'Edovia, Inc.',
             'display_name': 'Screens',
             'name': 'Screens',
             'unattended_install': True},
 'verbose': 4}
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://updates.edovia.com/com.edovia.screens4.mac/appcast.xml'}}
SparkleUpdateInfoProvider: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://updates.edovia.com/com.edovia.screens4.mac/appcast.xml']
SparkleUpdateInfoProvider: Version retrieved from appcast: 1605208907
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 4.8
SparkleUpdateInfoProvider: Found URL https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip
{'Output': {'url': 'https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip',
            'version': '4.8'}}
URLDownloader
{'Input': {'filename': 'Screens-4.8.zip',
           'url': 'https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 196, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip', '--fail', '--output', '/Users/sysadmin/Library/AutoPkg/Cache/local.munki.Screens/downloads/tmpqxr4z5rw', '--header', 'If-None-Match: "1ea23ac-5b3d726a7f3f8"', '--header', 'If-Modified-Since: Wed, 11 Nov 2020 16:18:51 GMT']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 328, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 204, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 199, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip', '--fail', '--output', '/Users/sysadmin/Library/AutoPkg/Cache/local.munki.Screens/downloads/tmpqxr4z5rw', '--header', 'If-None-Match: "1ea23ac-5b3d726a7f3f8"', '--header', 'If-Modified-Since: Wed, 11 Nov 2020 16:18:51 GMT']' returned non-zero exit status 22.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip', '--fail', '--output', '/Users/sysadmin/Library/AutoPkg/Cache/local.munki.Screens/downloads/tmpqxr4z5rw', '--header', 'If-None-Match: "1ea23ac-5b3d726a7f3f8"', '--header', 'If-Modified-Since: Wed, 11 Nov 2020 16:18:51 GMT']' returned non-zero exit status 22.
Failed.
Receipt written to /Users/sysadmin/Library/AutoPkg/Cache/local.munki.Screens/receipts/local.munki-receipt-20201113-235114.plist

The following recipes failed:
    local.munki.Screens
        Error in local.munki.Screens: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.8b%25201605208907.zip', '--fail', '--output', '/Users/sysadmin/Library/AutoPkg/Cache/local.munki.Screens/downloads/tmpqxr4z5rw', '--header', 'If-None-Match: "1ea23ac-5b3d726a7f3f8"', '--header', 'If-Modified-Since: Wed, 11 Nov 2020 16:18:51 GMT']' returned non-zero exit status 22.

Nothing downloaded, packaged or imported.
```

**Expected behavior**
It should download the correct URL, instead of escaping the first part of an escape sequence and thus failing to download.

**Version (please complete the following information):**
 - OS version: 10.13.6
- AutoPkg Version: 2.2

**Comment by homebysix** [comment]
Hi @BioSehnsucht - This is rare, but it's more likely to be an issue with the Sparkle feed, not AutoPkg itself.

I have adjusted the Screens recipe to accommodate the escaped URL [here](https://github.com/autopkg/homebysix-recipes/pull/347). There's no action needed in the AutoPkg core codebase.

**Comment by BioSehnsucht** [comment]
@homebysix  Thanks. That change plus running `autopkg update-trust-info Screens.munki` so the change would be trusted solved the problem. I then had an issue with MunkiImporter thinking the version hadn't changed (this appears to be a problem with the app package itself) and had to force it to import it, but everything is solved here.
