### ISSUE TITLE
Autopkg run fails when adding recipe repo at beginning of run

### ISSUE THREAD

**Issue by TK5-Tim** [autopkg/autopkg#701]
**Describe the problem**
When running a Recipe Override on Autopkg with a parent recipe of a not yet added recipe repository it prompts the possibility to add that repo. After adding the repository to the local recipe repos the AutoPkg run crashes while trying to proceed. The problem mainly occurs when the recipe tries to access another recipe repo after adding one earlier in the run. 
The second recipe repo gets marked as not found although it is existent in the recipe search path. 

**Preferences contents**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
Provide the output of `defaults read com.github.autopkg`, or the contents of your external `--prefs` file. 
```
{
    "MUNKI_REPO" = "/Volumes/munki_repo_test";
    "RECIPE_REPOS" =     {
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes" =         {
            URL = "https://github.com/autopkg/andrewvalentine-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes" =         {
            URL = "https://github.com/autopkg/blackthroat-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes" =         {
            URL = "https://github.com/autopkg/bochoven-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes" =         {
            URL = "https://github.com/autopkg/gerardkok-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes" =         {
            URL = "https://github.com/autopkg/grahampugh-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes" =         {
            URL = "https://github.com/autopkg/hansen-m-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes" =         {
            URL = "https://github.com/autopkg/hjuutilainen-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes" =         {
            URL = "https://github.com/autopkg/homebysix-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes" =         {
            URL = "https://github.com/autopkg/joshua-d-miller-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes" =         {
            URL = "https://github.com/autopkg/nmcspadden-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes" =         {
            URL = "https://github.com/autopkg/novaksam-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.peshay-recipes" =         {
            URL = "https://github.com/autopkg/peshay-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes" =         {
            URL = "https://github.com/autopkg/rtrouton-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes" =         {
            URL = "https://github.com/autopkg/scriptingosx-recipes";
        };
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes" =         {
            URL = "https://github.com/autopkg/ygini-recipes";
        };
    };
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.peshay-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.ygini-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes",
        "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes"
    );
}

```
**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
```
autopkg run -vv local.munki.AdobeAcrobatDCUpdate                     
Didn't find a recipe for com.github.novaksam.download.AdobeAcrobatDCUpdate.
Search GitHub AutoPkg repos for a com.github.novaksam.download.AdobeAcrobatDCUpdate recipe? [y/n]: y
Found this recipe in repository: novaksam-recipes

Add recipe repo 'novaksam-recipes'? [y/n]: y 
Attempting git clone...

Adding ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'
  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes'

Processing local.munki.AdobeAcrobatDCUpdate...
Could not find parent recipe for com.github.joshua-d-miller.autopkg.munki.AdobeAcrobatDCUpdate
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2718, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2712, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2229, in run_recipes
    verify_parent_trust(recipe, override_dirs, search_dirs, options.verbose)
  File "/usr/local/bin/autopkg", line 1581, in verify_parent_trust
    actual_trust_info = get_trust_info(parent_recipe, search_dirs)
  File "/usr/local/bin/autopkg", line 1412, in get_trust_info
    parent_recipe_paths = recipe.get("PARENT_RECIPES", []) + [recipe["RECIPE_PATH"]]
AttributeError: 'NoneType' object has no attribute 'get'
```

**Expected behavior**
It was expected that the recipe would proceed with the download and import of the application after adding the unknown recipe. This behavior is also visible if you run the same command again with the recipe then already imported. 

**Version (please complete the following information):**
 - OS version: 11.0.1 (but also happened on 10.15.7)
- AutoPkg Version: 2.2

**Comment by homebysix** [comment]
I can also reproduce this problem.

1. Add repos required to create the override:

    ```
    % autopkg repo-add joshua-d-miller-recipes
    Attempting git clone...

    Adding ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes to RECIPE_SEARCH_DIRS...
    Updated search path:
      '.'
      '~/Library/AutoPkg/Recipes'
      '/Library/AutoPkg/Recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'

    % autopkg repo-add novaksam-recipes
    Attempting git pull...
    Already up to date.

    Updated search path:
      '.'
      '~/Library/AutoPkg/Recipes'
      '/Library/AutoPkg/Recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'
    ```

1. Make override:

    ```
    % autopkg make-override AdobeAcrobatDCUpdate.munki
    Override file saved to ~/Library/AutoPkg/RecipeOverrides/AdobeAcrobatDCUpdate.munki.recipe
    ```

1. Remove repos that contain the parents.

    ```
    % autopkg repo-delete novaksam-recipes
    % autopkg repo-delete joshua-d-miller-recipes
    ```

1. Try to run the override, specifying `y` when prompted to add repos.

    ```
    % autopkg run -vv AdobeAcrobatDCUpdate.munki
    Didn't find a recipe for com.github.joshua-d-miller.autopkg.munki.AdobeAcrobatDCUpdate.
    Search GitHub AutoPkg repos for a com.github.joshua-d-miller.autopkg.munki.AdobeAcrobatDCUpdate recipe? [y/n]: y
    Found this recipe in repository: joshua-d-miller-recipes

    Add recipe repo 'joshua-d-miller-recipes'? [y/n]: y
    Attempting git clone...

    Adding ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes to RECIPE_SEARCH_DIRS...
    Updated search path:
      '.'
      '~/Library/AutoPkg/Recipes'
      '/Library/AutoPkg/Recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'

    Didn't find a recipe for com.github.novaksam.download.AdobeAcrobatDCUpdate.
    Search GitHub AutoPkg repos for a com.github.novaksam.download.AdobeAcrobatDCUpdate recipe? [y/n]: y
    Found this recipe in repository: novaksam-recipes

    Add recipe repo 'novaksam-recipes'? [y/n]: y
    Attempting git clone...

    Adding ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes to RECIPE_SEARCH_DIRS...
    Updated search path:
      '.'
      '~/Library/AutoPkg/Recipes'
      '/Library/AutoPkg/Recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'
      '~/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes'

    Processing AdobeAcrobatDCUpdate.munki...
    Could not find parent recipe for com.github.joshua-d-miller.autopkg.munki.AdobeAcrobatDCUpdate
    Traceback (most recent call last):
      File "/usr/local/bin/autopkg", line 2718, in <module>
        sys.exit(main(sys.argv))
      File "/usr/local/bin/autopkg", line 2712, in main
        exit(subcommands[verb]["function"](argv))
      File "/usr/local/bin/autopkg", line 2229, in run_recipes
        verify_parent_trust(recipe, override_dirs, search_dirs, options.verbose)
      File "/usr/local/bin/autopkg", line 1581, in verify_parent_trust
        actual_trust_info = get_trust_info(parent_recipe, search_dirs)
      File "/usr/local/bin/autopkg", line 1412, in get_trust_info
        parent_recipe_paths = recipe.get("PARENT_RECIPES", []) + [recipe["RECIPE_PATH"]]
    AttributeError: 'NoneType' object has no attribute 'get'
    ```

I'll try to take a look at the root cause soon.

**Comment by nmcspadden** [comment]
Quoting kwik from #autopkg in Slack's concise summation of the issue:
> it looks as if the issue is: Recipe C inherits recipe B, asks to include the repo with B and then finds its missing the parent for B, namely A and never checks to include that repo. locate_recipe() is only run for the first?

I think the logic to find parent repos here is messy and will take some effort to unpack.

**Comment by autopkg-bala04** [comment]
When running the recipe, getting the following error. Please help me out.

autopkg@MacBook-Pro ~ % autopkg make-override Google_Chrome.jamf
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2783, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2779, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 1973, in make_override
    plistlib.dump(override_dict, f)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 970, in dump
    writer.write(value)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 402, in write
    self.write_value(value)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 425, in write_value
    self.write_dict(value)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 472, in write_dict
    self.write_value(value)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 425, in write_value
    self.write_dict(value)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 472, in write_dict
    self.write_value(value)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/plistlib.py", line 440, in write_value
    raise TypeError("unsupported type: %s" % type(value))
TypeError: unsupported type: <class 'NoneType'

**Comment by homebysix** [comment]
@autopkg-bala04 - Please open a new issue, as yours isn't related to this one.
