### ISSUE TITLE
GitHubReleasesInfoProvider.py should provide better curl binary feedback

### ISSUE THREAD

**Issue by jgstew** [autopkg/autopkg#763]
**Describe the problem**
The unspecified "CURL_PATH" for [GitHubReleasesInfoProvider.py](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/GitHubReleasesInfoProvider.py) uses a default path for cURL of `/usr/bin/curl` instead of using `find_binary("curl", self.env)` like [URLGetter.py](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLGetter.py#L46) does.

**Preferences contents**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
Provide the output of `defaults read com.github.autopkg`, or the contents of your external `--prefs` file. 

**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*

Example: https://github.com/jgstew/jgstew-recipes/blob/main/Audacity/Audacity-Win.download.recipe.yaml
```
python ..\autopkg\Code\autopkg run com.github.jgstew.download.Audacity-Win -vvvv
WARNING: Library 'xattr' unavailable. Defining no-op implementation.
WARNING: Failed 'from Foundation import NSDictionary' in autopkglib.MunkiInstallsItemsCreator
WARNING: Failed 'from Foundation import CFPreferencesCopyAppValue' in autopkglib.MunkiSetDefaultCatalog
WARNING: Failed 'from Foundation import NSPredicate' in autopkglib.StopProcessingIf

--------------------------------------------------------------------------------
-- WARNING: AutoPkg is not completely functional on platforms other than OS X --
--------------------------------------------------------------------------------

Processing com.github.jgstew.download.Audacity-Win...
WARNING: com.github.jgstew.download.Audacity-Win is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.3.2',
 'NAME': 'Audacity',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': 'C:\\Users\\james/Library/AutoPkg/Cache\\com.github.jgstew.download.Audacity-Win',
 'RECIPE_DIR': 'C:\\Users\\james\\Documents\\_Code\\jgstew-recipes\\Audacity',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': 'C:\\Users\\james\\Documents\\_Code\\jgstew-recipes\\Audacity\\Audacity-Win.download.recipe.yaml',
 'RECIPE_REPOS': {'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.homebysix-recipes',
                        'C:\\Users\\james\\Library\\AutoPkg\\RecipeRepos\\com.github.autopkg.recipes'],
 'TYPE': 'exe',
 'verbose': 4}
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '.*\\.exe$', 'github_repo': 'audacity/audacity'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
WARNING: path given in the 'CURL_PATH' environment: '/usr/bin/curl' either doesn't exist or is not executable! Continuing search for usable 'curl'.
Traceback (most recent call last):
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 840, in process
    self.env = processor.process()
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 626, in process
    self.main()
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\GitHubReleasesInfoProvider.py", line 191, in main
    releases = self.get_releases(self.env["github_repo"])
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\GitHubReleasesInfoProvider.py", line 122, in get_releases
    (releases, status) = github.call_api(releases_uri)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\github\__init__.py", line 276, in call_api
    resp_data = json.load(f)
  File "C:\Users\james\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\james\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 85160: character maps to <undefined>
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 840, in process
    self.env = processor.process()
'charmap' codec can't decode byte 0x9d in position 85160: character maps to <undefined>
Failed.
Receipt written to C:\Users\james/Library/AutoPkg/Cache\com.github.jgstew.download.Audacity-Win\receipts\com.github.jgstew.download-receipt-20210809-121316.plist

The following recipes failed:
    com.github.jgstew.download.Audacity-Win
        Error in com.github.jgstew.download.Audacity-Win: Processor: GitHubReleasesInfoProvider: Error: 'charmap' codec can't decode byte 0x9d in position 85160: character maps to <undefined>

Nothing downloaded, packaged or imported.
```

**Expected behavior**
For GitHubReleasesInfoProvider.py to not require OS specific overrides to function. As it is now, the default option only works on some platforms, where setting `CURL_PATH` in the recipe to something OS specific, for Windows for instance, then causes that recipe to only run correctly on Windows. Ideally it would be more OS agnostic like URLGetter.py by searching for curl by default instead of using an OS specific hard coded path. 

**Version (please complete the following information):**
 - OS version: Windows 10 or any platform that does not have a default path for curl of `/usr/bin/curl`
- AutoPkg Version: 2.3.1

**Comment by jgstew** [comment]
Weird, when I try this same thing with other examples, it works, but it fails for this one specific example.

**Comment by jgstew** [comment]
Now that I look at this more closely, this may not be a curl path issue, but rather a decode error from the HTML. Maybe it needs to be a binary download in this case? or similar?

I guess the real issue is that it should provide better feedback when curl is being found automatically on PATH so I can tell what curl binary it is using, something to follow up the warning message:

`WARNING: path given in the 'CURL_PATH' environment: '/usr/bin/curl' either doesn't exist or is not executable! Continuing search for usable 'curl'.`

**Comment by jgstew** [comment]
Now that I've walked through the code a bit more, I realize that it is using https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/github/__init__.py which in turn does use URLGetter
