### ISSUE TITLE
GitHubReleasesInfoProvider.py - curl exit status 22 

### ISSUE THREAD

**Issue by skoobasteeve** [autopkg/autopkg#773]
**Describe the problem**
Not sure if this is a bug or just a configuration problem, but I have a Github Actions machine that's getting an error running the Brackets.download.recipe and I'm not sure how to debug it. 

**Preferences contents**
The only things we're changing in the Github Actions run is the below:
```
  defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS $(pwd)/RecipeOverrides/
  defaults write com.github.autopkg RECIPE_REPO_DIR $(pwd)/repos/
  defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
  defaults write com.github.autopkg JSS_URL $JSS_URL
  defaults write com.github.autopkg API_USERNAME $JSS_USERNAME
  defaults write com.github.autopkg API_PASSWORD $JSS_PASSWORD
```

**AutoPkg output**
```
Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3+json', '--url', 'https://api.github.com/repos/adobe/brackets/releases', '--output', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmptnij1nwi']' returned non-zero exit status 22.
Processing RecipeOverrides/Brackets-riskified.jss.recipe...
Failed.
{'API_PASSWORD': '***',
 'API_USERNAME': '***',
 'AUTOPKG_VERSION': '2.3.1',
 'CATEGORY': 'Computer Science',
 'FAIL_RECIPES_WITHOUT_TRUST_INFO': True,
 'GROUP_NAME': 'Brackets-update-smart',
 'GROUP_TEMPLATE': 'SmartGroupTemplate-brackets.xml',
 'JSS_URL': '***',
 'NAME': 'Brackets',
 'PARENT_RECIPES': ['/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.jss-recipes/Brackets/Brackets.jss.recipe',
                    '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes/Recipes '
                    '- pkg/Brackets.pkg.recipe',
                    '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes/Recipes '
                    '- Download/Brackets.download.recipe'],
 'POLICY_CATEGORY': 'Applications - Onboarding',
 'POLICY_TEMPLATE': 'PolicyTemplate-brackets.xml',
 'RECIPE_CACHE_DIR': '/Users/runner/Library/AutoPkg/Cache/local.jss.Brackets-riskified',
 'RECIPE_DIR': '/Users/runner/work/it-autopkg/it-autopkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['/Users/runner/work/it-autopkg/it-autopkg/RecipeOverrides/'],
 'RECIPE_PATH': '/Users/runner/work/it-autopkg/it-autopkg/RecipeOverrides/Brackets-riskified.jss.recipe',
 'RECIPE_REPOS': {'/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.Darkomen78-recipes': {'URL': 'https://github.com/autopkg/Darkomen78-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.MLBZ521-recipes': {'URL': 'https://github.com/autopkg/MLBZ521-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.Tecnico1931-recipes': {'URL': 'https://github.com/autopkg/Tecnico1931-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.ahousseini-recipes': {'URL': 'https://github.com/autopkg/ahousseini-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.bnpl-recipes': {'URL': 'https://github.com/autopkg/bnpl-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.chilcote-recipes': {'URL': 'https://github.com/autopkg/chilcote-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.crystalllized-recipes': {'URL': 'https://github.com/autopkg/crystalllized-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.foigus-recipes': {'URL': 'https://github.com/autopkg/foigus-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.gmarnin-recipes': {'URL': 'https://github.com/autopkg/gmarnin-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.jss-recipes': {'URL': 'https://github.com/autopkg/jss-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.justinrummel-recipes': {'URL': 'https://github.com/autopkg/justinrummel-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.killahquam-recipes': {'URL': 'https://github.com/autopkg/killahquam-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.mosen-recipes': {'URL': 'https://github.com/autopkg/mosen-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes': {'URL': 'https://github.com/autopkg/novaksam-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.skoobasteeve-recipes': {'URL': 'https://github.com/autopkg/skoobasteeve-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.smithjw-recipes': {'URL': 'https://github.com/autopkg/smithjw-recipes.git'},
                  '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.wholtz-recipes': {'URL': 'https://github.com/autopkg/wholtz-recipes.git'}},
 'RECIPE_REPO_DIR': '/Users/runner/work/it-autopkg/it-autopkg/repos/',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.Darkomen78-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.MLBZ521-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.ahousseini-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.bnpl-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.chilcote-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.crystalllized-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.dataJAR-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.foigus-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.gmarnin-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.hansen-m-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.homebysix-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.jss-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.justinrummel-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.keeleysam-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.killahquam-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.mosen-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.rtrouton-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.skoobasteeve-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.smithjw-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.wholtz-recipes',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.Tecnico1931-recipes',
                        'RecipeOverrides',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.jss-recipes/Brackets',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes/Recipes '
                        '- pkg',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.jss-recipes/Brackets',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes/Recipes '
                        '- pkg',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes/Recipes '
                        '- pkg',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.jss-recipes/Brackets',
                        '/Users/runner/work/it-autopkg/it-autopkg/repos/com.github.autopkg.novaksam-recipes/Recipes '
                        '- pkg'],
 'SELF_SERVICE_DESCRIPTION': 'An open source code editor for web designers and '
                             'front-end developers. Supported by Adobe.',
 'SELF_SERVICE_ICON': 'Brackets.png',
 'STOP_IF_NO_JSS_UPLOAD': 'False',
 'verbose': 4}
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'Brackets\\.Release\\.[\\d\\.]+\\.dmg',
           'github_repo': 'adobe/brackets'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 177, in execute_curl
    errors=errors,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3+json', '--url', 'https://api.github.com/repos/adobe/brackets/releases', '--output', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmptnij1nwi']' returned non-zero exit status 22.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/GitHubReleasesInfoProvider.py", line 191, in main
    releases = self.get_releases(self.env["github_repo"])
  File "/Library/AutoPkg/autopkglib/GitHubReleasesInfoProvider.py", line 122, in get_releases
    (releases, status) = github.call_api(releases_uri)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 269, in call_api
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 150, in download_with_curl
    p_stdout, p_stderr, retcode = self.execute_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 180, in execute_curl
    raise ProcessorError(e)
autopkglib.ProcessorError: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3+json', '--url', 'https://api.github.com/repos/adobe/brackets/releases', '--output', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmptnij1nwi']' returned non-zero exit status 22.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Receipt written to /Users/runner/Library/AutoPkg/Cache/local.jss.Brackets-riskified/receipts/Brackets-riskified.jss-receipt-20211101-213632.plist

The following recipes failed:
    RecipeOverrides/Brackets-riskified.jss.recipe
        Error in local.jss.Brackets-riskified: Processor: GitHubReleasesInfoProvider: Error: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3+json', '--url', 'https://api.github.com/repos/adobe/brackets/releases', '--output', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmptnij1nwi']' returned non-zero exit status 22.

Nothing downloaded, packaged or imported.
```

**Expected behavior**
Download from Github usually completes without issue, now it's not. 

**Version (please complete the following information):**
 - OS version: 10.15.7, Github Actions
- AutoPkg Version: 2.3.1

**Comment by homebysix** [comment]
@skoobasteeve Does this error happen consistently, or intermittently? I'm having no trouble running the Brackets.download recipe at this time, and when I try `curl -sIL "https://api.github.com/repos/adobe/brackets/releases"
` I get a 200 status code back.

I notice you're not using a GitHub token for AutoPkg. Could you be hitting GitHub's rate limit?

**Comment by skoobasteeve** [comment]
That was exactly the issue! Thanks for the tip. I imagine the IP that Github Actions uses is shared by l lots of other instances, and thus was rate limited. 

Thank you for the help!
