### ISSUE TITLE
MunkiImport fails on M1 with "ImportError: Framework CoreServices could not be found" #1121

### ISSUE THREAD

**Issue by zenopopovici** [autopkg/autopkg#790]
**Describe the problem**
I'm following up to: https://github.com/munki/munki/issues/1121 and https://github.com/autopkg/autopkg/issues/775.

I've tried this on a **freshly installed M1 system**. I spend a day trying to fix this, I would greatly appreciate any help.

##### System configuration
1. MacBook Pro M1 16GB RAM
2. macOS 12.2 (21D49)

##### Packages installed
1. `autopkg-2.3.1.pkg`
2. `munkitools-5.6.3.4401.pkg`
3.  XCode Developer Tools
4. Rosetta (it seems AutoPKG won't run without Rosetta).
5. Copied a simple Munki recipe

##### Affected munki versions
- `>=5.6.2`
-  `v5.6.1` does not have this issue. 

I tried debugging the issue, however, my knowledge of Python is limited.  I'm guessing this is happening because of the inclusion of the `info` library as shown here: https://github.com/munki/munki/compare/v5.6.1...v5.6.2, as this was the only change in the release.

**Preferences contents**
```
{
    "RECIPE_REPOS" =     {
        "/Users/Zeno/Library/AutoPkg/RecipeRepos/Graffino.SysOps-AutoPkg" =         {
            URL = "https://XXXXXXXXXXXXXXXXXXXXXX:x-oauth-basic@github.com/Graffino/SysOps-AutoPkg.git";
        };
    };
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/Zeno/Library/AutoPkg/RecipeRepos/Graffino.SysOps-AutoPkg"
    );
}
```

**AutoPkg output**
```bash
graffino@Graffinos-MBP Alfred % autopkg run Alfred.munki.recipe -vvv 
WARNING: Did not load any default preferences.
Processing Alfred.munki.recipe...
WARNING: Alfred.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.3.1',
 'DOWNLOAD_URL': 'https://XXXXXXXXXXXXX.XXX/autopkg/alfred.pkg',
 'MUNKI_CATEGORY': 'Ulitilites',
 'MUNKI_REPO': '""',
 'MUNKI_REPO_PLUGIN': 'SimpleMDMRepo',
 'MUNKI_REPO_SUBDIR': 'apps',
 'NAME': 'Alfred',
 'PARENT_RECIPES': ['/Users/graffino/Downloads/Alfred/Alfred.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred',
 'RECIPE_DIR': '/Users/graffino/Downloads/Alfred',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/graffino/Downloads/Alfred/Alfred.munki.recipe',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        ''],
 'extract_icon': True,
 'pkginfo': {'blocking_applications': ['Alfred.app'],
             'catalogs': ['Manual • Munki • Everyone'],
             'category': 'Ulitilites',
             'description': 'Alfred is an award-winning app for macOS which '
                            'boosts your efficiency with hotkeys, keywords, '
                            'text expansion and more. Search your Mac and the '
                            'web, and be more productive with custom actions '
                            'to control your Mac.',
             'developer': 'Running with Crayons',
             'display_name': 'Alfred*',
             'name': 'Alfred',
             'unattended_install': True},
 'verbose': 3}
URLDownloader
{'Input': {'filename': 'Alfred.pkg',
           'url': 'https://packages.graffino.net/autopkg/alfred.pkg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/downloads/Alfred.pkg
{'Output': {'pathname': '/Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/downloads/Alfred.pkg'}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
MunkiImporter
{'Input': {'MUNKI_REPO': '""',
           'MUNKI_REPO_PLUGIN': 'SimpleMDMRepo',
           'extract_icon': True,
           'pkg_path': '/Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/downloads/Alfred.pkg',
           'pkginfo': {'blocking_applications': ['Alfred.app'],
                       'catalogs': ['Manual • Munki • Everyone'],
                       'category': 'Ulitilites',
                       'description': 'Alfred is an award-winning app for '
                                      'macOS which boosts your efficiency with '
                                      'hotkeys, keywords, text expansion and '
                                      'more. Search your Mac and the web, and '
                                      'be more productive with custom actions '
                                      'to control your Mac.',
                       'developer': 'Running with Crayons',
                       'display_name': 'Alfred*',
                       'name': 'Alfred',
                       'unattended_install': True},
           'repo_subdirectory': 'apps'}}
MunkiImporter: No value supplied for MUNKILIB_DIR, setting default value of: /usr/local/munki
MunkiImporter: No value supplied for force_munki_repo_lib, setting default value of: False
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 16, in __init__
    from munkilib.admin import munkiimportlib
  File "/usr/local/munki/munkilib/admin/munkiimportlib.py", line 34, in <module>
    from .. import osinstaller
  File "/usr/local/munki/munkilib/osinstaller.py", line 47, in <module>
    from . import info
  File "/usr/local/munki/munkilib/info.py", line 37, in <module>
    import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/LaunchServices/__init__.py", line 9, in <module>
    import CoreServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/__init__.py", line 15, in <module>
    from CoreServices import LaunchServices
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/CoreServices/LaunchServices/__init__.py", line 18, in <module>
    "/System/Library/Frameworks/CoreServices.framework/CoreServices"
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 136, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 130, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/site-packages/objc/_dyld.py", line 98, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 292, in main
    self.env["force_munki_repo_lib"],
  File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 168, in _fetch_repo_library
    munki_repo, munki_repo_plugin, munkilib_dir, repo_subdirectory
  File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLib.py", line 20, in __init__
    f"munkilib import error: {str(err)}\nMunki tools version 3.2.0.3462 or "
autopkglib.ProcessorError: munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
Failed.
Receipt written to /Users/graffino/Library/AutoPkg/Cache/com.graffino.autopkg.munki.alfred/receipts/Alfred.munki-receipt-20220207-074021.plist

The following recipes failed:
    Alfred.munki.recipe
        Error in com.graffino.autopkg.munki.alfred: Processor: MunkiImporter: Error: munkilib import error: Framework CoreServices could not be found
        Munki tools version 3.2.0.3462 or later is required.

Nothing downloaded, packaged or imported.
```

**Expected behavior**
It should not throw up an error.

**Version (please complete the following information):**
- OS version: 12.2 (21D49)
- AutoPkg Version: 2.3.1

**Comment by Bretterteig** [comment]
This issue is not limited to M1 devices.

With munki switching from python2 to their own build python3 the PyObjC CoreServices framework is not included anymore. 

I am affected as well :^)

**Comment by Bretterteig** [comment]
Not limited to M1.

Affected as well.

**Comment by Bretterteig** [comment]
Narrowing it down: On my side the problem occurs when munkiimporter is run with extract_icon set to true.
I do not know if it still fits the issue above.

**Comment by amichelic** [comment]
This problem seems to be connected to the version of Python that's bundled with Autopkg, and the version of pyobjc. The Munki bundle had similar problem, and was updated to a fresher Python version to solve the problem: [#999](https://github.com/munki/munki/issues/999)
I did manually apply this commit of pyobj to the _dyld.py file that was bundled with AutoPkg, and this made the problem go away: [29d76ac1](https://github.com/ronaldoussoren/pyobjc/commit/29d76ac10bef807a6c0c5660cdf8cc02e8cfc1ed)

**Comment by gregneagle** [comment]
Neither I nor Nick can repo this issue. Here's a successful session on an Apple silicon Mac:
```
bash-3.2$ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 7459.101.2
      OS Loader Version: 7459.101.2
      <the rest redacted>

bash-3.2$ sudo managedsoftwareupdate -V
5.6.3.4401

bash-3.2$ autopkg version
2.4.1

bash-3.2$ autopkg info
Current preferences:
{'MUNKI_REPO': '/Users/Shared/munki_repo',
 'RECIPE_REPOS': {'/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes'},
                  '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.gregneagle-recipes': {'URL': 'https://github.com/autopkg/gregneagle-recipes'},
                  '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.gregneagle-recipes',
                        '/Users/gneagle/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes']}

bash-3.2$ autopkg run GoogleChrome.munki
Processing GoogleChrome.munki...

The following new items were imported into Munki:
    Name          Version        Catalogs    Pkginfo Path                           Pkg Repo Path                        Icon Repo Path  
    ----          -------        --------    ------------                           -------------                        --------------  
    GoogleChrome  100.0.4896.60  production  apps/GoogleChrome-100.0.4896.60.plist  apps/GoogleChrome-100.0.4896.60.dmg                  
```

**Comment by zenopopovici** [comment]
> bash-3.2$ autopkg run GoogleChrome.munki

Just making sure: 
It seems that you're running autopkg without `-k extract_icon=True`, can you run: `autopkg run GoogleChrome.munki -k extract_icon=True` and see if you have the same results?

**Comment by gregneagle** [comment]
That would be a really important bit of data. I see no mention of using `-k extract_icon=True` in the original issue report...

**Comment by gregneagle** [comment]
This might be a key bit of info in the original issue report:
`'MUNKI_REPO_PLUGIN': 'SimpleMDMRepo',`

**Comment by gregneagle** [comment]
```
bash-3.2$ autopkg run GoogleChrome.munki -k extract_icon=True
Processing GoogleChrome.munki...
munkilib import error: Framework CoreServices could not be found
Munki tools version 3.2.0.3462 or later is required.
Failed.

The following recipes failed:
    GoogleChrome.munki
        Error in com.disneyanimation.autopkg.munki.google-chrome: Processor: MunkiImporter: Error: munkilib import error: Framework CoreServices could not be found
        Munki tools version 3.2.0.3462 or later is required.

Nothing downloaded, packaged or imported.
```

So here's what I think is happening: when autopkg is told to use a custom MUNKI_REPO_PLUGIN or when it is told to extract an icon, it calls _Munki_ code in /usr/local/munki/munkilib. This code in turn was tested with Munki's own Python, which is 3.9.x and Universal, and includes PyObjC 7.2.  Right now, autopkg's Python is version 3.7.5, Intel-only, and includes PyObjC 6.0.1. When that version of Python attempts to run Munki's code that calls PyObjC, it fails.

So I believe the right fix is for a new release of autopkg that includes a Universal Python 3.9.x or later with PyObjC 7.2 or later.

Sadly, you can't easily work around the issue in the meantime using Munki's Python, as Munki's Python does not include the yaml module:
```
bash-3.2$ munki-python /usr/local/bin/autopkg run GoogleChrome.munki -k extract_icon=True
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 36, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by zenopopovici** [comment]
@gregneagle Sorry for the missing parameter, it was in the recipe file itself. 😮‍💨 

At least it is now reproducible. There is a workaround: downgrade `munki-tools` to `v5.6.1`. This is what I have been doing since the bug.

**Comment by gregneagle** [comment]
If you do that as a workaround, I'd recommend doing it _only_ on your autopkg runner, not your entire fleet. I'm not really understanding why that would work, though, as the basic issues are still present: autopkg has old Python and PyObjC compared to Munki.

**Comment by gregneagle** [comment]
Looking deeper I see it's because munkiimportlib imports osinstaller, which in turn imports info, which contains a relatively new is_apple_silicon() function. But info.py also imports LaunchServices (for use by another function in info.py), which triggers this error. So downgrading to a version of the munkitools that does not use info.is_apple_silicon() works around the issue with autopkg, at the expense of possibly breaking some actual Munki functionality on Apple silicon.

A better temporary workaround would be to copy a munkilb from Munki 5.6.1 somewhere else and then use the MUNKILIB_DIR preference to point to it. Then Munki itself could still be at version 5.6.3 or later.

**Comment by nmcspadden** [comment]
Can someone try to reproduce this with the newest 2.6.0 beta release? That should have addressed this issue.

**Comment by Bretterteig** [comment]
Fixed for me
