### ISSUE TITLE
SparkleUpdateInfoProvider fails with Rectangle.app appcast_url

### ISSUE THREAD

**Issue by PeetMcK** [autopkg/autopkg#839]
**Describe the problem**
SparkleUpdateInfoProvider cannot extract data from Rectangle.app's app cast_url ([https://rectangleapp.com/downloads/updates.xml](https://rectangleapp.com/downloads/updates.xml)). I

**Preferences contents**
Last login: Thu Nov 17 15:19:05 on ttys002
munkiadmin@ac-munkiadmin-m1 ~ % defaults read com.github.autopkg
```
{
    "CACHE_DIR" = "/Volumes/ac-munki-data/Library/AutoPkg/Cache";
    "GIT_PATH" = "/opt/homebrew/bin/git";
    "MUNKI_REPO" = "/Volumes/ac-munki-data/ac-munki/repo";
    "RECIPE_OVERRIDE_DIRS" = "/Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides";
    "RECIPE_REPOS" =     {
        "/Users/munkiadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes.git";
        };
       ...
        "/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.peetinc.autopkg-recipes" =         {
            URL = "https://github.com/peetinc/autopkg-recipes.git";
        };
    };
    "RECIPE_REPO_DIR" = "/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos";
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/munkiadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
       ...
    );
    "VIRUSTOTAL_SLEEP_SECONDS" = 10;
}
```

**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
```
`munkiadmin@ac-munkiadmin-m1 ~ % autopkg run -vvv /Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides/Rectangle.munki.recipe
Processing /Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides/Rectangle.munki.recipe...
{'AUTOPKG_VERSION': '2.7',
 'CACHE_DIR': '/Volumes/ac-munki-data/Library/AutoPkg/Cache',
 'CATEGORY': 'Utilities',
 'GIT_PATH': '/opt/homebrew/bin/git',
 'MUNKI_REPO': '/Volumes/ac-munki-data/ac-munki/repo',
 'MUNKI_REPO_SUBDIR': 'apps/RyanHanson',
 'NAME': 'Rectangle',
 'PARENT_RECIPES': ['/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.autopkg.peetinc-recipes/Rectangle/Rectangle.munki.recipe',
                    '/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.autopkg.peetinc-recipes/Rectangle/Rectangle.download.recipe'],
 'RECIPE_CACHE_DIR': '/Volumes/ac-munki-data/Library/AutoPkg/Cache/local.munki.Rectangle',
 'RECIPE_DIR': '/Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['/Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides/Rectangle.munki.recipe',
 'RECIPE_REPOS': {'/Users/munkiadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  ...
                  '/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.peetinc.autopkg-recipes': {'URL': 'https://github.com/peetinc/autopkg-recipes.git'}},
 'RECIPE_REPO_DIR': '/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/munkiadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        ...
                        '/Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides',
                        '/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.autopkg.peetinc-recipes/Rectangle',
                        '/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.autopkg.peetinc-recipes/Rectangle',
                        '/Volumes/ac-munki-data/Library/AutoPkg/RecipeRepos/com.github.autopkg.peetinc-recipes/Rectangle'],
 'VIRUSTOTAL_SLEEP_SECONDS': 10,
 'pkginfo': {'blocking_applications': [],
             'catalogs': ['testing'],
             'category': 'Utilities',
             'description': 'Move and resize windows on macOS with keyboard '
                            'shortcuts. Rectangle is a window management app '
                            'based on <a '
                            "href='//alternativeto.net/software/spectacle/'>Spectacle</a>, "
                            'written in <a '
                            "href='//alternativeto.net/software/swift-programming-language/'>Apple "
                            'Swift</a>.',
             'developer': 'Ryan Hanson',
             'display_name': 'Rectangle',
             'name': 'Rectangle',
             'postinstall_script': '#!/bin/bash \n'
                                   '\t\t\t\t\n'
                                   'AppName="Rectangle" \n'
                                   'AppPath="/Applications/$AppName.app" \n'
                                   'ConsoleUSER=$(stat -f "%Su" '
                                   '/dev/console) \n'
                                   'RestartApp="/Users/Shared/.Restart$AppName"\n'
                                   '\n'
                                   'if [ -f $RestartApp ]; then\n'
                                   '\tsu "$ConsoleUSER" -c "open -a $AppPath"\n'
                                   '\trm $RestartApp\n'
                                   'fi\n'
                                   '\n'
                                   'exit 0\n'
                                   '\t\t\t\t',
             'preinstall_script': '#!/bin/bash \n'
                                  '\t\t\t\t\n'
                                  'AppName="Rectangle"\n'
                                  'AppPath="/Applications/$AppName.app"\n'
                                  'ConsoleUSER=$(stat -f "%Su" /dev/console)\n'
                                  'RestartApp="/Users/Shared/.Restart$AppName"\n'
                                  '\n'
                                  'if [ -f $RestartApp ]; then\n'
                                  '\trm $RestartApp\n'
                                  'fi\n'
                                  '\n'
                                  'if ( pgrep "$AppName" ) then\n'
                                  'sudo -u $ConsoleUSER /usr/bin/osascript '
                                  '<<AppleScript\n'
                                  '\tquit app "$AppName"\n'
                                  'AppleScript\n'
                                  'sleep 3\n'
                                  'killall "$AppName" > /dev/null 2>&1\n'
                                  'touch $RestartApp\n'
                                  'fi\n'
                                  '\n'
                                  'exit 0\n'
                                  '\t\t\t\t',
             'unattended_install': True},
 'verbose': 3}
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://rectangleapp.com/downloads/updates.xml'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/SparkleUpdateInfoProvider.py", line 301, in main
    items = self.parse_feed_data(data)
  File "/Library/AutoPkg/autopkglib/SparkleUpdateInfoProvider.py", line 224, in parse_feed_data
    item["version"] = self.determine_version(enclosure, item["url"])
  File "/Library/AutoPkg/autopkglib/SparkleUpdateInfoProvider.py", line 191, in determine_version
    raise ProcessorError("Can't extract version info from item in feed!")
autopkglib.ProcessorError: Can't extract version info from item in feed!
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
Can't extract version info from item in feed!
Failed.
Receipt written to /Volumes/ac-munki-data/Library/AutoPkg/Cache/local.munki.Rectangle/receipts/Rectangle.munki-receipt-20221117-150445.plist

The following recipes failed:
    /Volumes/ac-munki-data/Library/AutoPkg/RecipeOverrides/Rectangle.munki.recipe
        Error in local.munki.Rectangle: Processor: SparkleUpdateInfoProvider: Error: Can't extract version info from item in feed!

Nothing downloaded, packaged or imported.
```

**Expected behavior**
For `SparkleUpdateInfoProvider` to parse [https://rectangleapp.com/downloads/updates.xml](https://rectangleapp.com/downloads/updates.xml). I'm not sure what the change is to updates.xml as `SparkleUpdateInfoProvider` used to parse the xml. My Python abilities are weak, but it's obvious that it's failing at line 301, `self.parse_feed_data`. I've validated the "updates.xml" to ensure there wasn't bad formatting that Sparkle ignored. 

**Version (please complete the following information):**
 - OS version: [13.0.1]
- AutoPkg Version: 2.7

**Comment by homebysix** [comment]
This feed seems like it's not following the Sparkle format consistently. The version information is sometimes used within the item, and sometime used within the item's enclosure.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/7801391/202862289-2216af6c-3758-476c-b935-49225c73bee3.png">

This may be because the Sparkle project documentation has changed its guidance on where to put the version information:

> Note on sparkle:version: Our previous documentation used to recommend specifying sparkle:version (and sparkle:shortVersionString) as part of the enclosure item. While this works fine, for overall consistency we now recommend specifying them as top level items instead as shown here. This is supported across all versions of Sparkle.

([source](https://sparkle-project.org/documentation/publishing/))

So it seems that SparkleUpdateInfoProvider should be updated accordingly. I'll take a shot.

**Comment by PeetMcK** [comment]
@homebysix Many thanks. Tested with the Sparkle version of the Rectangle recipe and voila, works as expected.
