### ISSUE TITLE
recipe-map calculation breaks autopkg if a recipe exists with a syntax error

### ISSUE THREAD

**Issue by grahampugh** [autopkg/autopkg#869]
If you have a broken recipe in any of the repos in the cache, recipe-map will fail to build, and autopkg cannot be run. It's not very easy to find which recipe/repo is the culprit, so remediation can be painful. I have reproduced by forking a repo I didn't have before and then adding it (twice, due to #868).

**Preferences contents**
Same as in #868

**AutoPkg output**
```
% autopkg repo-add grahampugh/macprince-recipes
Attempting git clone for https://github.com/grahampugh/macprince-recipes...

Adding /Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.grahampugh.macprince-recipes to RECIPE_SEARCH_DIRS...
Updating recipe map...
Updated search paths:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.ahousseini-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.andredb90-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.bochoven-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.crystalllized-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.drewdiver-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.eth-its.autopkg-mac-recipes-yaml'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.faumac-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.gerardkok-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.its-unibas-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.jbaker10-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.jlehikoinen-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.neilmartin83-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.nmcspadden-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.nzmacgeek-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.paul-cossey-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.peshay-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.peterkelm-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.precursorca-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.sebtomasi-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.tbridge-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.davidbpirie-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.jaharmi-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.kitzy-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.erikng-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.kevinmcox-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.swy-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.zentral-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.grahampugh.jamf-upload'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.tallfunnyjew-recipes'
  '/Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.grahampugh.macprince-recipes'

% autopkg repo-update grahampugh/macprince-recipes
Attempting git pull for /Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.grahampugh.macprince-recipes...
Already up to date.

Recalculating the recipe map...
WARNING: plist error for /Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.grahampugh.macprince-recipes/DeepL/DeepL.download.recipe: Invalid file
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2715, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2711, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 818, in repo_update
    calculate_recipe_map()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 523, in calculate_recipe_map
    write_recipe_map_to_disk()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 557, in write_recipe_map_to_disk
    json.dump(
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 353, in _iterencode_dict
    items = sorted(dct.items())
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Expected behavior**
Either an invalid recipe should be ignored (not added to the map) or a valid warning should be outputted that says which recipe is invalid, so that it can be easily remediated.

**Version (please complete the following information):**
 - OS version: 14.0b3
- AutoPkg Version: 2.8 RC

**Comment by nmcspadden** [comment]
Should be fixed with https://github.com/autopkg/autopkg/commit/3b072ffc27f169c658da0de81cf68608ce79cc84
