### ISSUE TITLE
autopkg repo-add fails if there are no existing repos

### ISSUE THREAD

**Issue by grahampugh** [autopkg/autopkg#871]
When setting up AutoPkg fresh, the `autopkg repo-add` verb fails.

**Preferences contents**
```
% defaults read com.github.autopkg                    
{
    "FAIL_RECIPES_WITHOUT_TRUST_INFO" = 0;
    "GITHUB_TOKEN" = "xxx";
    "GIT_PATH" = "/usr/bin/git";
}
```

**AutoPkg output**
```
% autopkg repo-add grahampugh-recipes
Attempting git pull for /Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes...
Already up to date.

Adding /Users/gpugh/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes to RECIPE_SEARCH_DIRS...
Updating recipe map with new repo...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2715, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2711, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 703, in repo_add
    calculate_recipe_map(extra_search_dirs=[new_recipe_repo_dir])
  File "/Library/AutoPkg/autopkglib/__init__.py", line 509, in calculate_recipe_map
    for search_dir in get_pref("RECIPE_SEARCH_DIRS") + extra_search_dirs:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

**Expected behavior**
The `repo-add` verb should be able to create the `RECIPE_SEARCH_DIRS` array and `RECIPE_REPOS` dictionary if they don't already exist.

**Current workaround**
I found that manually adding these using the following command causes the `repo-add` verb to work:
```
defaults write com.github.autopkg RECIPE_REPOS -dict
defaults write com.github.autopkg RECIPE_SEARCH_DIRS -array
```

**Version (please complete the following information):**
 - OS version: 13.5, 14.0 (tried on two systems)
- AutoPkg Version: 2.8.1 RC

**Comment by jgstew** [comment]
This seems related: https://github.com/autopkg/autopkg/issues/786

**Comment by nmcspadden** [comment]
This was fixed at some point in the past and does not currently exhibit in RC6+.
