### ISSUE TITLE
2.8.1 RC5 - URL processor errors causing recipes to fail

### ISSUE THREAD

**Issue by ggeerraalldd** [autopkg/autopkg#875]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
After upgrading to AutoPkg 2.8.1 RC5, many of my recipes are failing. All recipe errors are related to URLs (URLTextSearcher, URL providers, SparkleUpdateInfoProvider, SourceForgeURLProvider).

**Preferences contents**
```
defaults read com.github.autopkg
{
    "CACHE_DIR" = "/Users/admin/Library/AutoPkg/Cache";
    "GIT_PATH" = "/Library/Developer/CommandLineTools/usr/bin/git";
    "MUNKI_REPO" = "/Users/Shared/munki/repo";
    "RECIPE_OVERRIDE_DIRS" = "/Users/admin/Library/AutoPkg/RecipeOverrides";
    "RECIPE_REPOS" =     {
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes" =         {
            URL = "https://github.com/autopkg/apizz-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes" =         {
            URL = "https://github.com/autopkg/dataJAR-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes" =         {
            URL = "https://github.com/autopkg/grahamgilbert-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes" =         {
            URL = "https://github.com/autopkg/grahampugh-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes" =         {
            URL = "https://github.com/autopkg/hansen-m-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes" =         {
            URL = "https://github.com/autopkg/hjuutilainen-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes" =         {
            URL = "https://github.com/autopkg/homebysix-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes" =         {
            URL = "https://github.com/autopkg/jessepeterson-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes" =         {
            URL = "https://github.com/autopkg/joshua-d-miller-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes" =         {
            URL = "https://github.com/autopkg/keeleysam-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.kevinmcox-recipes" =         {
            URL = "https://github.com/autopkg/kevinmcox-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes" =         {
            URL = "https://github.com/autopkg/killahquam-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes" =         {
            URL = "https://github.com/autopkg/munkireport-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes" =         {
            URL = "https://github.com/autopkg/nstrauss-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes" =         {
            URL = "https://github.com/autopkg/recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes" =         {
            URL = "https://github.com/autopkg/rtrouton-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.ggeerraalldd.autopkg-recipes" =         {
            URL = "https://github.com/ggeerraalldd/autopkg-recipes.git";
        };
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.notverypc.autopkg-recipes" =         {
            URL = "https://github.com/notverypc/autopkg-recipes.git";
        };
    };
    "RECIPE_REPO_DIR" = "/Users/admin/Library/AutoPkg/RecipeRepos";
    "RECIPE_SEARCH_DIRS" =     (
        ".",
        "~/Library/AutoPkg/Recipes",
        "/Library/AutoPkg/Recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.kevinmcox-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.ggeerraalldd.autopkg-recipes",
        "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.notverypc.autopkg-recipes"
    );
}
```
**AutoPkg output**

```
autopkg run -vvvv VLC.munki
Looking for VLC.munki...
Found VLC.munki in recipe map overrides
Looking for com.github.autopkg.munki.VLC...
Found com.github.autopkg.munki.VLC in recipe map
Looking for com.github.autopkg.download.VLC...
Found com.github.autopkg.download.VLC in recipe map
**load_recipe time: 0.0008382500091101974
Processing VLC.munki...
Looking for com.github.autopkg.munki.VLC...
Found com.github.autopkg.munki.VLC in recipe map
Looking for com.github.autopkg.download.VLC...
Found com.github.autopkg.download.VLC in recipe map
Looking for com.github.autopkg.download.VLC...
Found com.github.autopkg.download.VLC in recipe map
{'ARCHITECTURE': 'universal',
 'AUTOPKG_VERSION': '2.8.1',
 'CACHE_DIR': '/Users/admin/Library/AutoPkg/Cache',
 'GIT_PATH': '/Library/Developer/CommandLineTools/usr/bin/git',
 'MUNKI_REPO': '/Users/Shared/munki/repo',
 'MUNKI_REPO_SUBDIR': 'apps/VLC',
 'NAME': 'VLC',
 'PARENT_RECIPES': ['/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.munki.recipe',
                    '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes/VLC/VLC.download.recipe'],
 'RECIPE_CACHE_DIR': '/Users/admin/Library/AutoPkg/Cache/local.munki.VLC',
 'RECIPE_DIR': '/Users/admin/Library/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['/Users/admin/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/admin/Library/AutoPkg/RecipeOverrides/VLC.munki.recipe',
 'RECIPE_REPOS': {'/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes': {'URL': 'https://github.com/autopkg/apizz-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes': {'URL': 'https://github.com/autopkg/grahamgilbert-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes': {'URL': 'https://github.com/autopkg/grahampugh-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes': {'URL': 'https://github.com/autopkg/jessepeterson-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.kevinmcox-recipes': {'URL': 'https://github.com/autopkg/kevinmcox-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes': {'URL': 'https://github.com/autopkg/killahquam-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes': {'URL': 'https://github.com/autopkg/munkireport-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes': {'URL': 'https://github.com/autopkg/nstrauss-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.ggeerraalldd.autopkg-recipes': {'URL': 'https://github.com/ggeerraalldd/autopkg-recipes.git'},
                  '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.notverypc.autopkg-recipes': {'URL': 'https://github.com/notverypc/autopkg-recipes.git'}},
 'RECIPE_REPO_DIR': '/Users/admin/Library/AutoPkg/RecipeRepos',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.kevinmcox-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.nstrauss-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.ggeerraalldd.autopkg-recipes',
                        '/Users/admin/Library/AutoPkg/RecipeRepos/com.github.notverypc.autopkg-recipes'],
 'pkginfo': {'catalogs': ['testing'],
             'category': 'Multimedia',
             'description': 'VLC is a free and open source cross-platform '
                            'multimedia player and framework that plays most '
                            'multimedia files as well as DVD, Audio CD, VCD, '
                            'and various streaming protocols.',
             'developer': 'The VideoLAN Project',
             'display_name': 'VLC Media Player',
             'name': 'VLC',
             'unattended_install': True},
 'verbose': 4}
URLTextSearcher
{'Input': {'re_pattern': 'href="\\/\\/get\\.videolan\\.org\\/vlc\\/([\\d\\.]+)\\/macosx\\/vlc-[\\d\\.]+-universal\\.dmg"',
           'result_output_var_name': 'version',
           'url': 'https://www.videolan.org/vlc/download-macosx.html'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1080, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 863, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 118, in main
    curl_cmd = self.prepare_curl_cmd()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 89, in prepare_curl_cmd
    curl_cmd = super().prepare_curl_cmd()
TypeError: URLGetter.prepare_curl_cmd() missing 5 required positional arguments: 'method', 'accept', 'headers', 'data', and 'temp_content'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 1080, in process
    self.env = processor.process()
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.VLC/receipts/VLC-receipt-20230810-160053.plist

The following recipes failed:
    VLC.munki
        Error in local.munki.VLC: Processor: URLTextSearcher: Error: URLGetter.prepare_curl_cmd() missing 5 required positional arguments: 'method', 'accept', 'headers', 'data', and 'temp_content'

Nothing downloaded, packaged or imported.
```

**Expected behavior**
Recipes should process URLs for downloading software. All 2.8.x prereleases have worked until this latest beta.

**Version (please complete the following information):**
 - OS version: 13.5
- AutoPkg Version: 2.8.1 RC5

**Comment by nmcspadden** [comment]
This is fixed in https://github.com/autopkg/autopkg/commit/c33a1a36e8598b17204d5fc5f5221a9a37825d36.
