### ISSUE TITLE
3.0.0RC1: Suggested GitHub search causes crash

### ISSUE THREAD

**Issue by jazzace** [autopkg/autopkg#887]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
When AutoPkg cannot find the recipe the user has requested to run in the v3.0 recipe map, it asks if it should search GitHub AutoPkg repos for that recipe. If you type `y` for Yes, AutoPkg crashes.

**Preferences contents**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
Tested both with and without `GITHUB_TOKEN` set in Preferences (as per AutoPkg 2 style). 

**AutoPkg output**
*BE SURE TO SANITIZE ANY SENSITIVE DATA SUCH AS PASSWORDS OR ADDRESSES.*
```
% autopkg run --ignore-parent-trust-verification-errors iStopMotionOld.pkg
Looking for iStopMotionOld.pkg...
Did not find iStopMotionOld.pkg in recipe map
Maybe you meant iStopMotion3.pkg?
Search GitHub AutoPkg repos for an iStopMotionOld.pkg recipe? [y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2704, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2700, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 2119, in run_recipes
    recipe = load_recipe(
  File "/usr/local/bin/autopkg", line 280, in load_recipe
    recipe_file = locate_recipe(
  File "/usr/local/bin/autopkg", line 220, in locate_recipe
    results_items = GitHubSession().search_for_name(name)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 89, in __init__
    self.autopkg_org = self.session.get_organization("autopkg")
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/MainClass.py", line 329, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", f"/orgs/{login}")
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Expected behaviuor**
Searching GitHub as prompted would not cause a crash.

**Version (please complete the following information):**
 - OS version: 13.5.1
- AutoPkg Version: 3.0.0RC1

**Comment by nmcspadden** [comment]
I think this happens if you don't have a valid auth token when it tries to auth to GitHub. Let me try a few scenarios - expired token, no token, valid token (which I know works).

**Comment by nmcspadden** [comment]
Yep, this is exactly what happens if you have an expired token.

**Comment by nmcspadden** [comment]
This is now handled better in https://github.com/autopkg/autopkg/commit/9e43eb488c029cfb833c7c5bd7e8f1e5a25ad550.

If you have an invalid/expired token:
```
% ./autopkg search iStopMotion.pkg
Your GitHub token exists but is invalid, please re-issue a new personal access token: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```
