### ISSUE TITLE
Cannot substitute `Int` only `Str` in recipe

### ISSUE THREAD

**Issue by jgstew** [autopkg/autopkg#895]
**Describe the problem**

If you try to substitute anything other than a string using %substitution% within a recipe, autopkg throws an error, even for things like `Int` or `Boolean` that are easily represented as strings.

As far as I know this has ALWAYS been the case with autopkg, but it is quite annoying.

Consider this recipe example:

```
---
Description: Test Int Subtitution - failing test
Identifier: com.github.jgstew.test.IntSubtitution
Input:
  NAME: IntSubtitutionTest
  Number: 123
MinimumVersion: "2.3"
Process:
  - Processor: EndOfCheckPhase
    Arguments:
      test_string: "%Number%"
```

**Preferences contents**

N/A

**AutoPkg output**

```
**load_recipe time: 0.007173467020038515
Processing C:\Users\james\Documents\_Code\jgstew-recipes\Test-Recipes\IntSubtitution.test.recipe.yaml...
WARNING: C:\Users\james\Documents\_Code\jgstew-recipes\Test-Recipes\IntSubtitution.test.recipe.yaml is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
EndOfCheckPhase
Traceback (most recent call last):
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 2725, in <module>
    sys.exit(main(sys.argv))
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 2721, in main
    return subcommands[verb]["function"](argv)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkg", line 2218, in run_recipes
    autopackager.process(recipe)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 866, in process
    processor.inject(step.get("Arguments", {}))
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 643, in inject
    update_data(self.env, key, value)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 488, in update_data
    a_dict[key] = do_variable_substitution(value)
  File "C:\Users\james\Documents\_Code\autopkg\Code\autopkglib\__init__.py", line 470, in do_variable_substitution
    item = RE_KEYREF.sub(getdata, item)
TypeError: sequence item 0: expected str instance, int found
```

**Expected behavior**
I expect autopkg to turn the `int` value into a string and substitute it into the variable.

**Version (please complete the following information):**
 - OS version: Win, Mac, Linux
- AutoPkg Version: All (3.0.0)

**Comment by jgstew** [comment]
The problem appears to be in here:

https://github.com/autopkg/autopkg/blob/e7bdfe1ab840a05e638968525413558181dc39d7/Code/autopkglib/__init__.py#L466-L470

**Comment by jgstew** [comment]
I don't actually know if this is a good idea or what the implications might be, but this does seem to fix this specific issue:

```
def update_data(a_dict, key, value):
    """Update a_dict keys with value. Existing data can be referenced
    by wrapping the key in %percent% signs."""

    def getdata(match):
        """Returns data from a match object"""
        return a_dict[match.group("key")]

    def getdata_str(match):
        """Returns string data from a match object"""
        return str(a_dict[match.group("key")])

    def do_variable_substitution(item):
        """Do variable substitution for item"""
        if isinstance(item, str):
            try:
                item = RE_KEYREF.sub(getdata, item)
            except KeyError as err:
                log_err(f"Use of undefined key in variable substitution: {err}")
            except TypeError as err:
                if "sequence item 0: expected str instance, int found" in str(err):
                    log(f"WARNING: subtituting int for string: {err}")
                    item = RE_KEYREF.sub(getdata_str, item)
                else:
                    raise err
        elif isinstance(item, (list, NSArray)):
            for index in range(len(item)):
                item[index] = do_variable_substitution(item[index])
        elif isinstance(item, (dict, NSDictionary)):
            # Modify a copy of the original
            if isinstance(item, dict):
                item_copy = item.copy()
            else:
                # Need to specify the copy is mutable for NSDictionary
                item_copy = item.mutableCopy()
            for key, value in list(item.items()):
                item_copy[key] = do_variable_substitution(value)
            return item_copy
        return item

    a_dict[key] = do_variable_substitution(value)
```

**Comment by jgstew** [comment]
I just submitted a PR that addresses this.

**Comment by jgstew** [comment]
I just realized I could also fix this issue by adding a processor:

- https://github.com/jgstew/jgstew-recipes/blob/main/SharedProcessors/VariableToString.py
- https://github.com/jgstew/jgstew-recipes/blob/main/Test-Recipes/VariableToString.test.recipe.yaml

I still think it would be nice if autopkg handled this transparently though.

**Comment by MLBZ521** [comment]
Just skiming through here and happened to come across this issue and it's related PR.  It looks very similar to the issue that I described and submitted a PR for in #911.  Does this sound accurate @jgstew ?

I'm also not sure if my PR has the correct "assumption" in mind when it comes to the expectations of substitution variables.

**Comment by MLBZ521** [comment]
I think it's both.

The Processor could be written to handle the types better....**but** if AutoPkg (proper) was updated to _**handle**_ `types` besides `str`, then Processors _**would**_ have to be written to better handle more than `str` types.

What my PR is proposing is:
  * Allow the recipe to be written with whatever type (e.g. value can be an `int` or `boolean`, etc.)
  * When the recipes is "loaded" those values are converted to `str`

This allows the Processors to still expect `str`s as they have traditionally done.

However, my PR may be to "heavy" on converting _everything_ to a `str`...

**Comment by MLBZ521** [comment]
But yes -- my PR is specifically for YAML only.

**Comment by gregneagle** [comment]
Maybe I'm misunderstanding but we definitely don't want autopkg to behave differently if a recipe happens to be formatted in yaml versus one formatted as a plist.

I think I agree that autopkg should just convert all values to strings before doing string substitution, even when doing so might have "interesting" consequences. (Like converting an array of strings into a string). Those consequences are really on the recipe writer to anticipate.

Alternately, we could convert only "scalar" types and not lists/arrays or dictionaries.

**Comment by MLBZ521** [comment]
I think we're on the same page Greg.  It's which direction would be the preferred way to go:
  * Convert all values to strings
    * This is what #911 does
  * Convert only scalar types to strings
    * I can either adjust #911 or open a separate PR to provide this functionality
    * I am leaning to this myself, just to make it "easier" to support these non-scalar types being values

**Comment by jgstew** [comment]
So the way I was proposing handling this is to attempt to convert variables into strings ONLY when doing substitution, but otherwise their type would be maintained.

I think this is important because I do have processors that set variables as non strings and operate on them as non strings intentionally (dictionaries, arrays)

I basically figured out some options for when the variable substitution function throws an error, then at that point attempt to convert the items to a string and do it again.

**Comment by MLBZ521** [comment]
Yeah, I think long term adjusting the `do_variable_substitution` logic would provide much more flexibility to recipe writers, regardless of the recipe language format.

In the short term, I've proposed an new solution for YAML recipes in #929.  This solution is the latter option in my previous reply on 12/7/2023.

**Comment by homebysix** [comment]
Should now be fixed in dev, via #1038. Thank you!
