### ISSUE TITLE
Everything breaks if ~/Library/AutoPkg is missing

### ISSUE THREAD

**Issue by nmcspadden** [autopkg/autopkg#898]
**THIS IS ONLY INTENDED FOR AUTOPKG BETAS.**

**Describe the problem**
You cannot add a repo if ~/Library/AutoPkg (the default parent path for the recipe map) doesn't exist, because it doesn't check if those folders exist before trying to write there. That means AutoPkg is functionally broken without the default parent folders.

**AutoPkg output**
```
Cannot read the recipe map file!
Attempting git clone for https://github.com/autopkg/apizz-recipes...

Adding /Users/runner/work/pipeline/pipeline/repos/com.github.autopkg.apizz-recipes to RECIPE_SEARCH_DIRS...
Updating recipe map with new repo...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2725, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2721, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 715, in repo_add
    calculate_recipe_map(extra_search_dirs=[new_recipe_repo_dir])
  File "/Library/AutoPkg/autopkglib/__init__.py", line 344, in calculate_recipe_map
    write_recipe_map_to_disk()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 384, in write_recipe_map_to_disk
    with open(DEFAULT_RECIPE_MAP, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/Library/AutoPkg/recipe_map.json'
Error: Process completed with exit code 1.
```

**Expected behavior**
Directory structure should be pre-populated at runtime, maybe?

**Version (please complete the following information):**
3.0.0RC2 currently experiences this.

**Comment by nmcspadden** [comment]
Doh, this is a duplicate of https://github.com/autopkg/autopkg/issues/893
