### ISSUE TITLE
autopkglib.ProcessorError: curl: (22) The requested URL returned error: 401

### ISSUE THREAD

**Issue by MalteKiefer** [autopkg/autopkg#946]
My version:

```bash
autopkg version
2.7.3
````

My repos:

```bash
 autopkg repo-list
/Users/XXX/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes (https://github.com/autopkg/dataJAR-recipes)
/Users/XX/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes (http://github.com/autopkg/recipes.git)
```

Looking for my recipe
```bash
 autopkg list-recipes | grep Logi
Jamf Connect Login Okta.munki
Jamf Connect Login.munki
LogiOptionsPlus.munki
Logitech Presentation.munki
LogiTune.download
LogiTune.munki
LogiTune.pkg
```

Trying to run LogiOptinsPlus 
```bash
 autopkg run -v LogiOptionsPlus.munki
Didn't find a recipe for com.github.wegotoeleven-recipes.pkg.LogiOptionsPlus.
Search GitHub AutoPkg repos for a com.github.wegotoeleven-recipes.pkg.LogiOptionsPlus recipe? [y/n]: y
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 172, in execute_curl
    result = subprocess.run(
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: application/vnd.github.v3.text-match+json', '--url', 'https://api.github.com/search/code?q=com.github.wegotoeleven-recipes.pkg.LogiOptionsPlus+extension:recipe+extension:plist+extension:yaml+user:autopkg+in:path,file&per_page=100', '--output', '/var/folders/ny/sk7jlm691rq_0_r75wbs3zm00000gp/T/tmpnyjmh16d']' returned non-zero exit status 22.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2786, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2782, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 2200, in run_recipes
    recipe = load_recipe(
  File "/usr/local/bin/autopkg", line 377, in load_recipe
    recipe = load_recipe(
  File "/usr/local/bin/autopkg", line 348, in load_recipe
    recipe_file = locate_recipe(
  File "/usr/local/bin/autopkg", line 283, in locate_recipe
    parent_repo = get_repository_from_identifier(name)
  File "/usr/local/bin/autopkg", line 208, in get_repository_from_identifier
    results = GitHubSession().search_for_name(identifier)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 193, in search_for_name
    results = self.code_search(query, use_token=use_token)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 216, in code_search
    (results, code) = self.call_api(
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 269, in call_api
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/github/__init__.py", line 150, in download_with_curl
    p_stdout, p_stderr, retcode = self.execute_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 181, in execute_curl
    raise ProcessorError(e.stderr) from e
autopkglib.ProcessorError: curl: (22) The requested URL returned error: 401
```

**Comment by homebysix** [comment]
I can reproduce the 401 error by calling the GitHub search API:

```
% /usr/bin/curl --head --location --silent --show-error --fail \
    --header "User-Agent: AutoPkg" \
    --header "Accept: application/vnd.github.v3.text-match+json" \
    --url "https://api.github.com/search/code?q=com.github.wegotoeleven-recipes.pkg.LogiOptionsPlus+extension:recipe+extension:plist+extension:yaml+user:autopkg+in:path,file&per_page=100"
HTTP/2 401 
server: GitHub.com
date: Tue, 25 Jun 2024 15:41:05 GMT
content-type: application/json; charset=utf-8
content-length: 255
cache-control: no-cache
vary: Accept, Accept-Encoding, Accept, X-Requested-With
x-github-media-type: github.v3; param=text-match; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
x-ratelimit-limit: 10
x-ratelimit-remaining: 8
x-ratelimit-reset: 1719330087
x-ratelimit-resource: search
x-ratelimit-used: 2
x-github-request-id: ED9A:38F0BB:C601F6:C78954:667AE511

curl: (22) The requested URL returned error: 401
```

When I make the same call again, this time providing a GitHub personal access token, I get a 200 response.

```
% /usr/bin/curl --head --location --silent --show-error --fail \
    --header "User-Agent: AutoPkg" \
    --header "Accept: application/vnd.github.v3.text-match+json" \
    --header "Authorization: Bearer $(cat ~/.autopkg_gh_token)" \
    --url "https://api.github.com/search/code?q=com.github.wegotoeleven-recipes.pkg.LogiOptionsPlus+extension:recipe+extension:plist+extension:yaml+user:autopkg+in:path,file&per_page=100"
HTTP/2 200 
server: GitHub.com
date: Tue, 25 Jun 2024 15:41:20 GMT
content-type: application/json; charset=utf-8
content-length: 22278
cache-control: no-cache
vary: Accept, Authorization, Cookie, X-GitHub-OTP
x-oauth-scopes: 
x-accepted-oauth-scopes: 
x-github-media-type: github.v3; param=text-match; format=json
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 10
x-ratelimit-remaining: 9
x-ratelimit-reset: 1719330140
x-ratelimit-used: 1
x-ratelimit-resource: code_search
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: ED9B:38F0BB:C64169:C7C942:667AE520
```

Are you using a [token](https://github.com/autopkg/autopkg/wiki/FAQ#how-do-i-provide-a-github-personal-access-token-to-autopkg) for your AutoPkg setup?

**Comment by MalteKiefer** [comment]
No, didn’t know that I needed one.

**Comment by homebysix** [comment]
I don't think GitHub used to require one for code search, but that may have [changed recently](https://github.com/orgs/community/discussions/77046).

**Comment by MalteKiefer** [comment]
Ok is there a way how to use the token described in the docs from autopkg

**Comment by homebysix** [comment]
Yes, on the FAQ page: https://github.com/autopkg/autopkg/wiki/FAQ#how-do-i-provide-a-github-personal-access-token-to-autopkg

**Comment by gregneagle** [comment]
I'll also point you towards the NOTE at the top of this page: https://github.com/autopkg/autopkg/wiki/Finding-Recipes
